// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/rdrs.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type FilterProto struct {
	Column               *string  `protobuf:"bytes,1,req,name=Column" json:"Column,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterProto) Reset()         { *m = FilterProto{} }
func (m *FilterProto) String() string { return proto.CompactTextString(m) }
func (*FilterProto) ProtoMessage()    {}
func (*FilterProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{1}
}

func (m *FilterProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterProto.Unmarshal(m, b)
}
func (m *FilterProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterProto.Marshal(b, m, deterministic)
}
func (m *FilterProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterProto.Merge(m, src)
}
func (m *FilterProto) XXX_Size() int {
	return xxx_messageInfo_FilterProto.Size(m)
}
func (m *FilterProto) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterProto.DiscardUnknown(m)
}

var xxx_messageInfo_FilterProto proto.InternalMessageInfo

func (m *FilterProto) GetColumn() string {
	if m != nil && m.Column != nil {
		return *m.Column
	}
	return ""
}

func (m *FilterProto) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type ReadColumnProto struct {
	Column               *string  `protobuf:"bytes,1,req,name=Column" json:"Column,omitempty"`
	DataReturnType       *string  `protobuf:"bytes,2,opt,name=DataReturnType" json:"DataReturnType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadColumnProto) Reset()         { *m = ReadColumnProto{} }
func (m *ReadColumnProto) String() string { return proto.CompactTextString(m) }
func (*ReadColumnProto) ProtoMessage()    {}
func (*ReadColumnProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{2}
}

func (m *ReadColumnProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadColumnProto.Unmarshal(m, b)
}
func (m *ReadColumnProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadColumnProto.Marshal(b, m, deterministic)
}
func (m *ReadColumnProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadColumnProto.Merge(m, src)
}
func (m *ReadColumnProto) XXX_Size() int {
	return xxx_messageInfo_ReadColumnProto.Size(m)
}
func (m *ReadColumnProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadColumnProto.DiscardUnknown(m)
}

var xxx_messageInfo_ReadColumnProto proto.InternalMessageInfo

func (m *ReadColumnProto) GetColumn() string {
	if m != nil && m.Column != nil {
		return *m.Column
	}
	return ""
}

func (m *ReadColumnProto) GetDataReturnType() string {
	if m != nil && m.DataReturnType != nil {
		return *m.DataReturnType
	}
	return ""
}

type PKReadRequestProto struct {
	DB                   *string            `protobuf:"bytes,1,req,name=DB" json:"DB,omitempty"`
	Table                *string            `protobuf:"bytes,2,req,name=Table" json:"Table,omitempty"`
	Filters              []*FilterProto     `protobuf:"bytes,3,rep,name=Filters" json:"Filters,omitempty"`
	ReadColumns          []*ReadColumnProto `protobuf:"bytes,4,rep,name=ReadColumns" json:"ReadColumns,omitempty"`
	OperationID          *string            `protobuf:"bytes,5,opt,name=OperationID" json:"OperationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *PKReadRequestProto) Reset()         { *m = PKReadRequestProto{} }
func (m *PKReadRequestProto) String() string { return proto.CompactTextString(m) }
func (*PKReadRequestProto) ProtoMessage()    {}
func (*PKReadRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{3}
}

func (m *PKReadRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PKReadRequestProto.Unmarshal(m, b)
}
func (m *PKReadRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PKReadRequestProto.Marshal(b, m, deterministic)
}
func (m *PKReadRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PKReadRequestProto.Merge(m, src)
}
func (m *PKReadRequestProto) XXX_Size() int {
	return xxx_messageInfo_PKReadRequestProto.Size(m)
}
func (m *PKReadRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_PKReadRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_PKReadRequestProto proto.InternalMessageInfo

func (m *PKReadRequestProto) GetDB() string {
	if m != nil && m.DB != nil {
		return *m.DB
	}
	return ""
}

func (m *PKReadRequestProto) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *PKReadRequestProto) GetFilters() []*FilterProto {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *PKReadRequestProto) GetReadColumns() []*ReadColumnProto {
	if m != nil {
		return m.ReadColumns
	}
	return nil
}

func (m *PKReadRequestProto) GetOperationID() string {
	if m != nil && m.OperationID != nil {
		return *m.OperationID
	}
	return ""
}

type ColumnValueProto struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ColumnValueProto) Reset()         { *m = ColumnValueProto{} }
func (m *ColumnValueProto) String() string { return proto.CompactTextString(m) }
func (*ColumnValueProto) ProtoMessage()    {}
func (*ColumnValueProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{4}
}

func (m *ColumnValueProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnValueProto.Unmarshal(m, b)
}
func (m *ColumnValueProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnValueProto.Marshal(b, m, deterministic)
}
func (m *ColumnValueProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnValueProto.Merge(m, src)
}
func (m *ColumnValueProto) XXX_Size() int {
	return xxx_messageInfo_ColumnValueProto.Size(m)
}
func (m *ColumnValueProto) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnValueProto.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnValueProto proto.InternalMessageInfo

func (m *ColumnValueProto) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type PKReadResponseProto struct {
	OperationID          *string                      `protobuf:"bytes,1,opt,name=OperationID" json:"OperationID,omitempty"`
	Code                 *int32                       `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Data                 map[string]*ColumnValueProto `protobuf:"bytes,3,rep,name=Data" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *PKReadResponseProto) Reset()         { *m = PKReadResponseProto{} }
func (m *PKReadResponseProto) String() string { return proto.CompactTextString(m) }
func (*PKReadResponseProto) ProtoMessage()    {}
func (*PKReadResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{5}
}

func (m *PKReadResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PKReadResponseProto.Unmarshal(m, b)
}
func (m *PKReadResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PKReadResponseProto.Marshal(b, m, deterministic)
}
func (m *PKReadResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PKReadResponseProto.Merge(m, src)
}
func (m *PKReadResponseProto) XXX_Size() int {
	return xxx_messageInfo_PKReadResponseProto.Size(m)
}
func (m *PKReadResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_PKReadResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_PKReadResponseProto proto.InternalMessageInfo

func (m *PKReadResponseProto) GetOperationID() string {
	if m != nil && m.OperationID != nil {
		return *m.OperationID
	}
	return ""
}

func (m *PKReadResponseProto) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *PKReadResponseProto) GetData() map[string]*ColumnValueProto {
	if m != nil {
		return m.Data
	}
	return nil
}

type BatchRequestProto struct {
	Operations           []*PKReadRequestProto `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *BatchRequestProto) Reset()         { *m = BatchRequestProto{} }
func (m *BatchRequestProto) String() string { return proto.CompactTextString(m) }
func (*BatchRequestProto) ProtoMessage()    {}
func (*BatchRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{6}
}

func (m *BatchRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchRequestProto.Unmarshal(m, b)
}
func (m *BatchRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchRequestProto.Marshal(b, m, deterministic)
}
func (m *BatchRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchRequestProto.Merge(m, src)
}
func (m *BatchRequestProto) XXX_Size() int {
	return xxx_messageInfo_BatchRequestProto.Size(m)
}
func (m *BatchRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_BatchRequestProto proto.InternalMessageInfo

func (m *BatchRequestProto) GetOperations() []*PKReadRequestProto {
	if m != nil {
		return m.Operations
	}
	return nil
}

type BatchResponseProto struct {
	Responses            []*PKReadResponseProto `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BatchResponseProto) Reset()         { *m = BatchResponseProto{} }
func (m *BatchResponseProto) String() string { return proto.CompactTextString(m) }
func (*BatchResponseProto) ProtoMessage()    {}
func (*BatchResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{7}
}

func (m *BatchResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchResponseProto.Unmarshal(m, b)
}
func (m *BatchResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchResponseProto.Marshal(b, m, deterministic)
}
func (m *BatchResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchResponseProto.Merge(m, src)
}
func (m *BatchResponseProto) XXX_Size() int {
	return xxx_messageInfo_BatchResponseProto.Size(m)
}
func (m *BatchResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_BatchResponseProto proto.InternalMessageInfo

func (m *BatchResponseProto) GetResponses() []*PKReadResponseProto {
	if m != nil {
		return m.Responses
	}
	return nil
}

type MemoryStatsProto struct {
	AllocationsCount     *int64   `protobuf:"varint,1,req,name=AllocationsCount" json:"AllocationsCount,omitempty"`
	DeallocationsCount   *int64   `protobuf:"varint,2,req,name=DeallocationsCount" json:"DeallocationsCount,omitempty"`
	BuffersCount         *int64   `protobuf:"varint,3,req,name=BuffersCount" json:"BuffersCount,omitempty"`
	FreeBuffers          *int64   `protobuf:"varint,4,req,name=FreeBuffers" json:"FreeBuffers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryStatsProto) Reset()         { *m = MemoryStatsProto{} }
func (m *MemoryStatsProto) String() string { return proto.CompactTextString(m) }
func (*MemoryStatsProto) ProtoMessage()    {}
func (*MemoryStatsProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{8}
}

func (m *MemoryStatsProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryStatsProto.Unmarshal(m, b)
}
func (m *MemoryStatsProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryStatsProto.Marshal(b, m, deterministic)
}
func (m *MemoryStatsProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryStatsProto.Merge(m, src)
}
func (m *MemoryStatsProto) XXX_Size() int {
	return xxx_messageInfo_MemoryStatsProto.Size(m)
}
func (m *MemoryStatsProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryStatsProto.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryStatsProto proto.InternalMessageInfo

func (m *MemoryStatsProto) GetAllocationsCount() int64 {
	if m != nil && m.AllocationsCount != nil {
		return *m.AllocationsCount
	}
	return 0
}

func (m *MemoryStatsProto) GetDeallocationsCount() int64 {
	if m != nil && m.DeallocationsCount != nil {
		return *m.DeallocationsCount
	}
	return 0
}

func (m *MemoryStatsProto) GetBuffersCount() int64 {
	if m != nil && m.BuffersCount != nil {
		return *m.BuffersCount
	}
	return 0
}

func (m *MemoryStatsProto) GetFreeBuffers() int64 {
	if m != nil && m.FreeBuffers != nil {
		return *m.FreeBuffers
	}
	return 0
}

type RonDBStatsProto struct {
	NdbObjectsCreationCount *int64   `protobuf:"varint,1,req,name=NdbObjectsCreationCount" json:"NdbObjectsCreationCount,omitempty"`
	NdbObjectsDeletionCount *int64   `protobuf:"varint,2,req,name=NdbObjectsDeletionCount" json:"NdbObjectsDeletionCount,omitempty"`
	NdbObjectsTotalCount    *int64   `protobuf:"varint,3,req,name=NdbObjectsTotalCount" json:"NdbObjectsTotalCount,omitempty"`
	NdbObjectsFreeCount     *int64   `protobuf:"varint,4,req,name=NdbObjectsFreeCount" json:"NdbObjectsFreeCount,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *RonDBStatsProto) Reset()         { *m = RonDBStatsProto{} }
func (m *RonDBStatsProto) String() string { return proto.CompactTextString(m) }
func (*RonDBStatsProto) ProtoMessage()    {}
func (*RonDBStatsProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{9}
}

func (m *RonDBStatsProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RonDBStatsProto.Unmarshal(m, b)
}
func (m *RonDBStatsProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RonDBStatsProto.Marshal(b, m, deterministic)
}
func (m *RonDBStatsProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RonDBStatsProto.Merge(m, src)
}
func (m *RonDBStatsProto) XXX_Size() int {
	return xxx_messageInfo_RonDBStatsProto.Size(m)
}
func (m *RonDBStatsProto) XXX_DiscardUnknown() {
	xxx_messageInfo_RonDBStatsProto.DiscardUnknown(m)
}

var xxx_messageInfo_RonDBStatsProto proto.InternalMessageInfo

func (m *RonDBStatsProto) GetNdbObjectsCreationCount() int64 {
	if m != nil && m.NdbObjectsCreationCount != nil {
		return *m.NdbObjectsCreationCount
	}
	return 0
}

func (m *RonDBStatsProto) GetNdbObjectsDeletionCount() int64 {
	if m != nil && m.NdbObjectsDeletionCount != nil {
		return *m.NdbObjectsDeletionCount
	}
	return 0
}

func (m *RonDBStatsProto) GetNdbObjectsTotalCount() int64 {
	if m != nil && m.NdbObjectsTotalCount != nil {
		return *m.NdbObjectsTotalCount
	}
	return 0
}

func (m *RonDBStatsProto) GetNdbObjectsFreeCount() int64 {
	if m != nil && m.NdbObjectsFreeCount != nil {
		return *m.NdbObjectsFreeCount
	}
	return 0
}

type StatRequestProto struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatRequestProto) Reset()         { *m = StatRequestProto{} }
func (m *StatRequestProto) String() string { return proto.CompactTextString(m) }
func (*StatRequestProto) ProtoMessage()    {}
func (*StatRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{10}
}

func (m *StatRequestProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatRequestProto.Unmarshal(m, b)
}
func (m *StatRequestProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatRequestProto.Marshal(b, m, deterministic)
}
func (m *StatRequestProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatRequestProto.Merge(m, src)
}
func (m *StatRequestProto) XXX_Size() int {
	return xxx_messageInfo_StatRequestProto.Size(m)
}
func (m *StatRequestProto) XXX_DiscardUnknown() {
	xxx_messageInfo_StatRequestProto.DiscardUnknown(m)
}

var xxx_messageInfo_StatRequestProto proto.InternalMessageInfo

type StatResponseProto struct {
	MemoryStats          *MemoryStatsProto `protobuf:"bytes,1,req,name=MemoryStats" json:"MemoryStats,omitempty"`
	RonDBStats           *RonDBStatsProto  `protobuf:"bytes,2,req,name=RonDBStats" json:"RonDBStats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StatResponseProto) Reset()         { *m = StatResponseProto{} }
func (m *StatResponseProto) String() string { return proto.CompactTextString(m) }
func (*StatResponseProto) ProtoMessage()    {}
func (*StatResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_c124a6640455fad3, []int{11}
}

func (m *StatResponseProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatResponseProto.Unmarshal(m, b)
}
func (m *StatResponseProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatResponseProto.Marshal(b, m, deterministic)
}
func (m *StatResponseProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatResponseProto.Merge(m, src)
}
func (m *StatResponseProto) XXX_Size() int {
	return xxx_messageInfo_StatResponseProto.Size(m)
}
func (m *StatResponseProto) XXX_DiscardUnknown() {
	xxx_messageInfo_StatResponseProto.DiscardUnknown(m)
}

var xxx_messageInfo_StatResponseProto proto.InternalMessageInfo

func (m *StatResponseProto) GetMemoryStats() *MemoryStatsProto {
	if m != nil {
		return m.MemoryStats
	}
	return nil
}

func (m *StatResponseProto) GetRonDBStats() *RonDBStatsProto {
	if m != nil {
		return m.RonDBStats
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "grpcserver.v1.Empty")
	proto.RegisterType((*FilterProto)(nil), "grpcserver.v1.FilterProto")
	proto.RegisterType((*ReadColumnProto)(nil), "grpcserver.v1.ReadColumnProto")
	proto.RegisterType((*PKReadRequestProto)(nil), "grpcserver.v1.PKReadRequestProto")
	proto.RegisterType((*ColumnValueProto)(nil), "grpcserver.v1.ColumnValueProto")
	proto.RegisterType((*PKReadResponseProto)(nil), "grpcserver.v1.PKReadResponseProto")
	proto.RegisterMapType((map[string]*ColumnValueProto)(nil), "grpcserver.v1.PKReadResponseProto.DataEntry")
	proto.RegisterType((*BatchRequestProto)(nil), "grpcserver.v1.BatchRequestProto")
	proto.RegisterType((*BatchResponseProto)(nil), "grpcserver.v1.BatchResponseProto")
	proto.RegisterType((*MemoryStatsProto)(nil), "grpcserver.v1.MemoryStatsProto")
	proto.RegisterType((*RonDBStatsProto)(nil), "grpcserver.v1.RonDBStatsProto")
	proto.RegisterType((*StatRequestProto)(nil), "grpcserver.v1.StatRequestProto")
	proto.RegisterType((*StatResponseProto)(nil), "grpcserver.v1.StatResponseProto")
}

func init() {
	proto.RegisterFile("api/rdrs.proto", fileDescriptor_c124a6640455fad3)
}

var fileDescriptor_c124a6640455fad3 = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xd1, 0x6e, 0xd3, 0x3c,
	0x18, 0xfd, 0x93, 0xb6, 0x9b, 0xfa, 0xf5, 0xa7, 0xeb, 0xbc, 0x0a, 0xa2, 0x5e, 0x40, 0xe7, 0x8b,
	0xa9, 0x42, 0x28, 0x83, 0x32, 0xa4, 0x09, 0x24, 0xb4, 0x75, 0xd9, 0xd0, 0x04, 0x6c, 0xc5, 0xab,
	0x26, 0xc4, 0x5d, 0x9a, 0x7a, 0xa3, 0x2c, 0x8d, 0x83, 0xe3, 0x4e, 0xea, 0x8b, 0xf0, 0x12, 0xdc,
	0xf2, 0x28, 0xbc, 0x03, 0x17, 0xbc, 0x04, 0x8a, 0x9d, 0x2e, 0xae, 0x9b, 0x31, 0xee, 0xe2, 0xe3,
	0x73, 0xce, 0xe7, 0xf3, 0xf9, 0x73, 0xa0, 0xee, 0xc7, 0xe3, 0x6d, 0x3e, 0xe2, 0x89, 0x1b, 0x73,
	0x26, 0x18, 0xba, 0x77, 0xc9, 0xe3, 0x20, 0xa1, 0xfc, 0x9a, 0x72, 0xf7, 0xfa, 0x19, 0x5e, 0x85,
	0xca, 0xe1, 0x24, 0x16, 0x33, 0xfc, 0x0a, 0x6a, 0x47, 0xe3, 0x50, 0x50, 0xde, 0x97, 0xb4, 0xfb,
	0xb0, 0x72, 0xc0, 0xc2, 0xe9, 0x24, 0x72, 0xac, 0xb6, 0xdd, 0xa9, 0x92, 0x6c, 0x85, 0x9a, 0x50,
	0x39, 0xf7, 0xc3, 0x29, 0x75, 0x6c, 0x09, 0xab, 0x05, 0xfe, 0x00, 0x6b, 0x84, 0xfa, 0x23, 0xc5,
	0xf9, 0xbb, 0xc1, 0x16, 0xd4, 0x3d, 0x5f, 0xf8, 0x84, 0x8a, 0x29, 0x8f, 0x06, 0xb3, 0x38, 0x75,
	0xb2, 0x3a, 0x55, 0x62, 0xa0, 0xf8, 0xa7, 0x05, 0xa8, 0xff, 0x36, 0x75, 0x25, 0xf4, 0xeb, 0x94,
	0x26, 0x42, 0xd9, 0xd6, 0xc1, 0xf6, 0x7a, 0x99, 0xa5, 0xed, 0xf5, 0xd2, 0xf3, 0x0c, 0xfc, 0x61,
	0x78, 0x73, 0x1e, 0xb9, 0x40, 0x3b, 0xb0, 0xaa, 0xc2, 0x24, 0x4e, 0xa9, 0x5d, 0xea, 0xd4, 0xba,
	0x2d, 0x77, 0x21, 0xb6, 0xab, 0x45, 0x25, 0x73, 0x2a, 0xda, 0x83, 0x5a, 0x9e, 0x22, 0x71, 0xca,
	0x52, 0xf9, 0xd0, 0x50, 0x1a, 0x39, 0x89, 0x2e, 0x41, 0x6d, 0xa8, 0x9d, 0xc6, 0x94, 0xfb, 0x62,
	0xcc, 0xa2, 0x63, 0xcf, 0xa9, 0xc8, 0x64, 0x3a, 0x84, 0xb7, 0xa0, 0xa1, 0xc8, 0xb2, 0x71, 0x2a,
	0x13, 0x82, 0xf2, 0x89, 0x3f, 0xa1, 0x8e, 0x25, 0xe9, 0xf2, 0x1b, 0xff, 0xb2, 0x60, 0x63, 0x1e,
	0x3f, 0x89, 0x59, 0x94, 0x64, 0x5c, 0xa3, 0x82, 0xb5, 0x54, 0x21, 0x75, 0x0b, 0xd8, 0x48, 0xb5,
	0xb5, 0x42, 0xe4, 0x37, 0xda, 0x83, 0x72, 0xda, 0xde, 0xac, 0x19, 0x4f, 0x8c, 0x48, 0x05, 0x75,
	0xdc, 0x94, 0x7e, 0x18, 0x09, 0x3e, 0x23, 0x52, 0xd9, 0xfa, 0x08, 0xd5, 0x1b, 0x08, 0x35, 0xa0,
	0x74, 0x45, 0x67, 0x59, 0xf1, 0xf4, 0x13, 0xbd, 0x80, 0xca, 0x75, 0x36, 0x16, 0x56, 0xa7, 0xd6,
	0x7d, 0x64, 0x54, 0x30, 0x23, 0x13, 0xc5, 0x7e, 0x69, 0xef, 0x5a, 0xf8, 0x1c, 0xd6, 0x7b, 0xbe,
	0x08, 0x3e, 0x2f, 0x5c, 0xf3, 0x3e, 0x00, 0x9b, 0x67, 0x4a, 0x1c, 0x4b, 0x1e, 0x7b, 0xf3, 0x96,
	0x63, 0xe7, 0x32, 0xa2, 0x89, 0xf0, 0x39, 0xa0, 0xcc, 0x57, 0xef, 0xdf, 0x1e, 0x54, 0x79, 0x06,
	0xcc, 0x7d, 0xf1, 0xdd, 0xed, 0x20, 0xb9, 0x08, 0xff, 0xb0, 0xa0, 0xf1, 0x9e, 0x4e, 0x18, 0x9f,
	0x9d, 0x09, 0x5f, 0x24, 0xca, 0xf6, 0x31, 0x34, 0xf6, 0xc3, 0x90, 0x05, 0xaa, 0xf6, 0x01, 0x9b,
	0x46, 0x42, 0x0e, 0x69, 0x89, 0x2c, 0xe1, 0xc8, 0x05, 0xe4, 0x51, 0xdf, 0x64, 0xdb, 0x92, 0x5d,
	0xb0, 0x83, 0x30, 0xfc, 0xdf, 0x9b, 0x5e, 0x5c, 0x50, 0x9e, 0x31, 0x4b, 0x92, 0xb9, 0x80, 0xa5,
	0x63, 0x71, 0xc4, 0x29, 0xcd, 0x30, 0xa7, 0x2c, 0x29, 0x3a, 0x84, 0x7f, 0x5b, 0xb0, 0x46, 0x58,
	0xe4, 0xf5, 0xb4, 0x53, 0xef, 0xc2, 0x83, 0x93, 0xd1, 0xf0, 0x74, 0xf8, 0x85, 0x06, 0x22, 0x39,
	0xe0, 0x54, 0x56, 0xd5, 0x0f, 0x7f, 0xdb, 0xf6, 0xa2, 0xd2, 0xa3, 0x21, 0xcd, 0x95, 0xb6, 0xa9,
	0x5c, 0xd8, 0x46, 0x5d, 0x68, 0xe6, 0x5b, 0x03, 0x26, 0xfc, 0x50, 0x4f, 0x55, 0xb8, 0x87, 0x9e,
	0xc2, 0x46, 0x8e, 0xa7, 0xa1, 0x94, 0x44, 0xa5, 0x2c, 0xda, 0xc2, 0x08, 0x1a, 0x69, 0x4e, 0x7d,
	0x38, 0xf0, 0x37, 0x0b, 0xd6, 0x15, 0xa8, 0x0f, 0xc4, 0x3e, 0xd4, 0xb4, 0xdb, 0x94, 0xb9, 0x97,
	0xe7, 0xd7, 0xbc, 0x6f, 0xa2, 0x6b, 0xd0, 0x6b, 0x80, 0xbc, 0xb3, 0x32, 0x7f, 0xc1, 0x6f, 0x63,
	0xb1, 0xf5, 0x44, 0x53, 0x74, 0xbf, 0xdb, 0x50, 0x95, 0x4b, 0x72, 0x78, 0x36, 0x40, 0x3b, 0x50,
	0xee, 0x8f, 0xa3, 0x4b, 0xd4, 0x34, 0x1c, 0xe4, 0x6f, 0xba, 0x55, 0x88, 0xe2, 0xff, 0xd0, 0x29,
	0xac, 0xa8, 0xb9, 0x45, 0x77, 0x3f, 0x93, 0xd6, 0x3f, 0x4c, 0x3c, 0x7a, 0x07, 0x15, 0xf9, 0x7c,
	0x50, 0xdb, 0x20, 0x2f, 0x3d, 0xd6, 0xd6, 0x66, 0x31, 0x43, 0x77, 0x3b, 0x86, 0x72, 0x9a, 0x15,
	0x99, 0x8d, 0x35, 0x2f, 0xa9, 0xd5, 0x2e, 0x24, 0x68, 0x56, 0xbd, 0xe7, 0xd0, 0x0c, 0xd8, 0xc4,
	0xe5, 0x2c, 0x1a, 0x0d, 0x35, 0x72, 0xaf, 0x2e, 0x5b, 0xf8, 0x86, 0xc7, 0x81, 0xe4, 0xf5, 0xad,
	0x4f, 0x55, 0x77, 0x3b, 0xbe, 0xba, 0xdc, 0xf6, 0xe3, 0xf1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x70, 0xba, 0xf9, 0xed, 0x06, 0x07, 0x00, 0x00,
}
