#!/bin/bash
# add to file  storage/ndb/clusterj/clusterj-test/src/main/java/testsuite/clusterj/AbstractClusterJTest.java
#        props.put("allowPublicKeyRetrieval", "true");

VERSION=21.04.9
CLUSTERJ_BUILD_DIR=/Volumes/ExtFileSystem/rondb_2104/err_build/storage/ndb/clusterj
MYSQL_CONNECTOR=/Users/mikael/mysql-connector-java-8.0.30/mysql-connector-java-8.0.30.jar
export LIBNDBCLIENT_PATH="/Volumes/ExtFileSystem/rondb_2104/err_build/lib"

#if  SINGLE_TEST is set then TEST_JAR is ignored
SINGLE_TEST="MultiDBUpdate2Test"
TEST_JAR="$CLUSTERJ_BUILD_DIR/clusterj-test/clusterj-test-$VERSION.jar"

if [ -n "$SINGLE_TEST" ]; then
  cd $CLUSTERJ_BUILD_DIR
  make
  cd $CLUSTERJ_BUILD_DIR/clusterj-test/target/classes
  jar cvf test.jar testsuite/clusterj/$SINGLE_TEST.class
  TEST_JAR=$(readlink -f test.jar)
fi

cd $CLUSTERJ_BUILD_DIR

ALL_JARS="$MYSQL_CONNECTOR"
ALL_JARS="$ALL_JARS:$CLUSTERJ_BUILD_DIR/clusterj-$VERSION.jar"
ALL_JARS="$ALL_JARS:$CLUSTERJ_BUILD_DIR/clusterj-test/clusterj-test-$VERSION.jar"
ALL_JARS="$ALL_JARS:$CLUSTERJ_BUILD_DIR/clusterj-api/clusterj-api-$VERSION.jar"
ALL_JARS="$ALL_JARS:$CLUSTERJ_BUILD_DIR/clusterj-tie/clusterj-tie-$VERSION.jar"
ALL_JARS="$ALL_JARS:$CLUSTERJ_BUILD_DIR/clusterj-core/clusterj-core-$VERSION.jar" 
ALL_JARS="$ALL_JARS:$CLUSTERJ_BUILD_DIR/../../../lib/libndbclient.dylib" 

echo "ALL_JARS = $ALL_JARS"

rm clusterj.properties
echo   "com.mysql.clusterj.connectstring=localhost:13000"               >>   clusterj.properties
echo   "com.mysql.clusterj.connect.retries=4"                           >>   clusterj.properties
echo   "com.mysql.clusterj.connect.delay=5"                             >>   clusterj.properties
echo   "com.mysql.clusterj.connect.verbose=1"                           >>   clusterj.properties
echo   "com.mysql.clusterj.connect.timeout.before=30"                   >>   clusterj.properties
echo   "com.mysql.clusterj.connect.timeout.after=20"                    >>   clusterj.properties
echo   "com.mysql.clusterj.jdbc.url=jdbc:mysql://localhost:13001/test"  >>   clusterj.properties
echo   "com.mysql.clusterj.jdbc.driver=com.mysql.cj.jdbc.Driver"        >>   clusterj.properties
echo   "com.mysql.clusterj.jdbc.username=root"                           >>   clusterj.properties
#echo   "com.mysql.clusterj.jdbc.password=hop"                           >>   clusterj.properties
echo   "com.mysql.clusterj.username=hop"                                >>   clusterj.properties
echo   "com.mysql.clusterj.password=hop"                                >>   clusterj.properties
echo   "com.mysql.clusterj.database=test"                               >>   clusterj.properties
echo   "com.mysql.clusterj.max.transactions=1024"                       >>   clusterj.properties
echo   "com.mysql.clusterj.connection.reconnect.timeout=3"              >>   clusterj.properties
java -cp $ALL_JARS -Djava.library.path=$LIBNDBCLIENT_PATH -Dclusterj.properties=$CLUSTERJ_BUILD_DIR/clusterj.properties testsuite.clusterj.AllTests  $TEST_JAR
