//
// This file is part of the RonDB REST API Server
// Copyright (c) 2022 Hopsworks AB
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

// TODO: Add comment why we're not using proto3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: api/rdrs.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{0}
}

type FilterProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column *string `protobuf:"bytes,1,req,name=Column" json:"Column,omitempty"`
	Value  *string `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
}

func (x *FilterProto) Reset() {
	*x = FilterProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterProto) ProtoMessage() {}

func (x *FilterProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterProto.ProtoReflect.Descriptor instead.
func (*FilterProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{1}
}

func (x *FilterProto) GetColumn() string {
	if x != nil && x.Column != nil {
		return *x.Column
	}
	return ""
}

func (x *FilterProto) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type ReadColumnProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column         *string `protobuf:"bytes,1,req,name=Column" json:"Column,omitempty"`
	DataReturnType *string `protobuf:"bytes,2,opt,name=DataReturnType,def=default" json:"DataReturnType,omitempty"`
}

// Default values for ReadColumnProto fields.
const (
	Default_ReadColumnProto_DataReturnType = string("default")
)

func (x *ReadColumnProto) Reset() {
	*x = ReadColumnProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadColumnProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadColumnProto) ProtoMessage() {}

func (x *ReadColumnProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadColumnProto.ProtoReflect.Descriptor instead.
func (*ReadColumnProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{2}
}

func (x *ReadColumnProto) GetColumn() string {
	if x != nil && x.Column != nil {
		return *x.Column
	}
	return ""
}

func (x *ReadColumnProto) GetDataReturnType() string {
	if x != nil && x.DataReturnType != nil {
		return *x.DataReturnType
	}
	return Default_ReadColumnProto_DataReturnType
}

type PKReadRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DB          *string            `protobuf:"bytes,1,req,name=DB" json:"DB,omitempty"`
	Table       *string            `protobuf:"bytes,2,req,name=Table" json:"Table,omitempty"`
	Filters     []*FilterProto     `protobuf:"bytes,3,rep,name=Filters" json:"Filters,omitempty"`
	ReadColumns []*ReadColumnProto `protobuf:"bytes,4,rep,name=ReadColumns" json:"ReadColumns,omitempty"`
	OperationID *string            `protobuf:"bytes,5,opt,name=OperationID" json:"OperationID,omitempty"`
}

func (x *PKReadRequestProto) Reset() {
	*x = PKReadRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PKReadRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKReadRequestProto) ProtoMessage() {}

func (x *PKReadRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKReadRequestProto.ProtoReflect.Descriptor instead.
func (*PKReadRequestProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{3}
}

func (x *PKReadRequestProto) GetDB() string {
	if x != nil && x.DB != nil {
		return *x.DB
	}
	return ""
}

func (x *PKReadRequestProto) GetTable() string {
	if x != nil && x.Table != nil {
		return *x.Table
	}
	return ""
}

func (x *PKReadRequestProto) GetFilters() []*FilterProto {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *PKReadRequestProto) GetReadColumns() []*ReadColumnProto {
	if x != nil {
		return x.ReadColumns
	}
	return nil
}

func (x *PKReadRequestProto) GetOperationID() string {
	if x != nil && x.OperationID != nil {
		return *x.OperationID
	}
	return ""
}

type ColumnValueProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
}

func (x *ColumnValueProto) Reset() {
	*x = ColumnValueProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnValueProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnValueProto) ProtoMessage() {}

func (x *ColumnValueProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnValueProto.ProtoReflect.Descriptor instead.
func (*ColumnValueProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{4}
}

func (x *ColumnValueProto) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type PKReadResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationID *string                      `protobuf:"bytes,1,opt,name=OperationID" json:"OperationID,omitempty"`
	Code        *int32                       `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	Message     *string                      `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Data        map[string]*ColumnValueProto `protobuf:"bytes,4,rep,name=Data" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (x *PKReadResponseProto) Reset() {
	*x = PKReadResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PKReadResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKReadResponseProto) ProtoMessage() {}

func (x *PKReadResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKReadResponseProto.ProtoReflect.Descriptor instead.
func (*PKReadResponseProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{5}
}

func (x *PKReadResponseProto) GetOperationID() string {
	if x != nil && x.OperationID != nil {
		return *x.OperationID
	}
	return ""
}

func (x *PKReadResponseProto) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *PKReadResponseProto) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *PKReadResponseProto) GetData() map[string]*ColumnValueProto {
	if x != nil {
		return x.Data
	}
	return nil
}

type BatchRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operations []*PKReadRequestProto `protobuf:"bytes,1,rep,name=operations" json:"operations,omitempty"`
}

func (x *BatchRequestProto) Reset() {
	*x = BatchRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequestProto) ProtoMessage() {}

func (x *BatchRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequestProto.ProtoReflect.Descriptor instead.
func (*BatchRequestProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{6}
}

func (x *BatchRequestProto) GetOperations() []*PKReadRequestProto {
	if x != nil {
		return x.Operations
	}
	return nil
}

type BatchResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*PKReadResponseProto `protobuf:"bytes,1,rep,name=responses" json:"responses,omitempty"`
}

func (x *BatchResponseProto) Reset() {
	*x = BatchResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponseProto) ProtoMessage() {}

func (x *BatchResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponseProto.ProtoReflect.Descriptor instead.
func (*BatchResponseProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{7}
}

func (x *BatchResponseProto) GetResponses() []*PKReadResponseProto {
	if x != nil {
		return x.Responses
	}
	return nil
}

type MemoryStatsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllocationsCount   *int64 `protobuf:"varint,1,req,name=AllocationsCount" json:"AllocationsCount,omitempty"`
	DeallocationsCount *int64 `protobuf:"varint,2,req,name=DeallocationsCount" json:"DeallocationsCount,omitempty"`
	BuffersCount       *int64 `protobuf:"varint,3,req,name=BuffersCount" json:"BuffersCount,omitempty"`
	FreeBuffers        *int64 `protobuf:"varint,4,req,name=FreeBuffers" json:"FreeBuffers,omitempty"`
}

func (x *MemoryStatsProto) Reset() {
	*x = MemoryStatsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemoryStatsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStatsProto) ProtoMessage() {}

func (x *MemoryStatsProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStatsProto.ProtoReflect.Descriptor instead.
func (*MemoryStatsProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{8}
}

func (x *MemoryStatsProto) GetAllocationsCount() int64 {
	if x != nil && x.AllocationsCount != nil {
		return *x.AllocationsCount
	}
	return 0
}

func (x *MemoryStatsProto) GetDeallocationsCount() int64 {
	if x != nil && x.DeallocationsCount != nil {
		return *x.DeallocationsCount
	}
	return 0
}

func (x *MemoryStatsProto) GetBuffersCount() int64 {
	if x != nil && x.BuffersCount != nil {
		return *x.BuffersCount
	}
	return 0
}

func (x *MemoryStatsProto) GetFreeBuffers() int64 {
	if x != nil && x.FreeBuffers != nil {
		return *x.FreeBuffers
	}
	return 0
}

type RonDBStatsProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NdbObjectsCreationCount *int64 `protobuf:"varint,1,req,name=NdbObjectsCreationCount" json:"NdbObjectsCreationCount,omitempty"`
	NdbObjectsDeletionCount *int64 `protobuf:"varint,2,req,name=NdbObjectsDeletionCount" json:"NdbObjectsDeletionCount,omitempty"`
	NdbObjectsTotalCount    *int64 `protobuf:"varint,3,req,name=NdbObjectsTotalCount" json:"NdbObjectsTotalCount,omitempty"`
	NdbObjectsFreeCount     *int64 `protobuf:"varint,4,req,name=NdbObjectsFreeCount" json:"NdbObjectsFreeCount,omitempty"`
}

func (x *RonDBStatsProto) Reset() {
	*x = RonDBStatsProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RonDBStatsProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RonDBStatsProto) ProtoMessage() {}

func (x *RonDBStatsProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RonDBStatsProto.ProtoReflect.Descriptor instead.
func (*RonDBStatsProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{9}
}

func (x *RonDBStatsProto) GetNdbObjectsCreationCount() int64 {
	if x != nil && x.NdbObjectsCreationCount != nil {
		return *x.NdbObjectsCreationCount
	}
	return 0
}

func (x *RonDBStatsProto) GetNdbObjectsDeletionCount() int64 {
	if x != nil && x.NdbObjectsDeletionCount != nil {
		return *x.NdbObjectsDeletionCount
	}
	return 0
}

func (x *RonDBStatsProto) GetNdbObjectsTotalCount() int64 {
	if x != nil && x.NdbObjectsTotalCount != nil {
		return *x.NdbObjectsTotalCount
	}
	return 0
}

func (x *RonDBStatsProto) GetNdbObjectsFreeCount() int64 {
	if x != nil && x.NdbObjectsFreeCount != nil {
		return *x.NdbObjectsFreeCount
	}
	return 0
}

type StatRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatRequestProto) Reset() {
	*x = StatRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequestProto) ProtoMessage() {}

func (x *StatRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequestProto.ProtoReflect.Descriptor instead.
func (*StatRequestProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{10}
}

type StatResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoryStats *MemoryStatsProto `protobuf:"bytes,1,req,name=MemoryStats" json:"MemoryStats,omitempty"`
	RonDBStats  *RonDBStatsProto  `protobuf:"bytes,2,req,name=RonDBStats" json:"RonDBStats,omitempty"`
}

func (x *StatResponseProto) Reset() {
	*x = StatResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponseProto) ProtoMessage() {}

func (x *StatResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponseProto.ProtoReflect.Descriptor instead.
func (*StatResponseProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{11}
}

func (x *StatResponseProto) GetMemoryStats() *MemoryStatsProto {
	if x != nil {
		return x.MemoryStats
	}
	return nil
}

func (x *StatResponseProto) GetRonDBStats() *RonDBStatsProto {
	if x != nil {
		return x.RonDBStats
	}
	return nil
}

// __________________  Health Operation _________________________
type HealthRequestProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HealthRequestProto) Reset() {
	*x = HealthRequestProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequestProto) ProtoMessage() {}

func (x *HealthRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequestProto.ProtoReflect.Descriptor instead.
func (*HealthRequestProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{12}
}

type HealthResponseProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RonDBHealth *int64 `protobuf:"varint,1,req,name=RonDBHealth" json:"RonDBHealth,omitempty"`
}

func (x *HealthResponseProto) Reset() {
	*x = HealthResponseProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rdrs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponseProto) ProtoMessage() {}

func (x *HealthResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_api_rdrs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponseProto.ProtoReflect.Descriptor instead.
func (*HealthResponseProto) Descriptor() ([]byte, []int) {
	return file_api_rdrs_proto_rawDescGZIP(), []int{13}
}

func (x *HealthResponseProto) GetRonDBHealth() int64 {
	if x != nil && x.RonDBHealth != nil {
		return *x.RonDBHealth
	}
	return 0
}

var File_api_rdrs_proto protoreflect.FileDescriptor

var file_api_rdrs_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x64, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x3b, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x5a, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x12, 0x2f, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x3a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x52, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x22, 0xd4, 0x01, 0x0a, 0x12, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x44, 0x42, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x02, 0x44, 0x42, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x34,
	0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x07, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x40, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x26, 0x0a, 0x10, 0x43, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x81, 0x02, 0x0a, 0x13, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x58, 0x0a, 0x09, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x35, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x56, 0x0a, 0x11, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x41, 0x0a, 0x0a, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x4b,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x52, 0x0a, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x56, 0x0a, 0x12,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x40, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x73, 0x22, 0xb4, 0x01, 0x0a, 0x10, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x0a, 0x10, 0x41, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x03, 0x52, 0x10, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x44, 0x65, 0x61, 0x6c, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x03, 0x52, 0x12, 0x44, 0x65, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0c, 0x42, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x72, 0x65,
	0x65, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0b,
	0x46, 0x72, 0x65, 0x65, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x22, 0xeb, 0x01, 0x0a, 0x0f,
	0x52, 0x6f, 0x6e, 0x44, 0x42, 0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x38, 0x0a, 0x17, 0x4e, 0x64, 0x62, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03,
	0x52, 0x17, 0x4e, 0x64, 0x62, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x17, 0x4e, 0x64, 0x62,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x17, 0x4e, 0x64, 0x62, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x14, 0x4e, 0x64, 0x62, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28,
	0x03, 0x52, 0x14, 0x4e, 0x64, 0x62, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x4e, 0x64, 0x62, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x73, 0x46, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x13, 0x4e, 0x64, 0x62, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x46, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01,
	0x0a, 0x11, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x41, 0x0a, 0x0b, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0b, 0x4d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x3e, 0x0a, 0x0a, 0x52, 0x6f, 0x6e, 0x44, 0x42, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6e, 0x44, 0x42,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x0a, 0x52, 0x6f, 0x6e, 0x44,
	0x42, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x13,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x6f, 0x6e, 0x44, 0x42, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x0b, 0x52, 0x6f, 0x6e, 0x44, 0x42, 0x48,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x32, 0xfc, 0x02, 0x0a, 0x09, 0x52, 0x6f, 0x6e, 0x44, 0x42, 0x52,
	0x45, 0x53, 0x54, 0x12, 0x34, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x06, 0x50, 0x4b, 0x52,
	0x65, 0x61, 0x64, 0x12, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x4b, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x4c, 0x0a, 0x05, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x49, 0x0a, 0x04, 0x53, 0x74, 0x61, 0x74,
	0x12, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x20, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x4f, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x21, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x42, 0x33, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x6f, 0x6e, 0x64,
	0x62, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x42, 0x0e, 0x52, 0x6f,
	0x6e, 0x44, 0x42, 0x47, 0x72, 0x70, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x09,
	0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
}

var (
	file_api_rdrs_proto_rawDescOnce sync.Once
	file_api_rdrs_proto_rawDescData = file_api_rdrs_proto_rawDesc
)

func file_api_rdrs_proto_rawDescGZIP() []byte {
	file_api_rdrs_proto_rawDescOnce.Do(func() {
		file_api_rdrs_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_rdrs_proto_rawDescData)
	})
	return file_api_rdrs_proto_rawDescData
}

var file_api_rdrs_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_rdrs_proto_goTypes = []interface{}{
	(*Empty)(nil),               // 0: grpcserver.v1.Empty
	(*FilterProto)(nil),         // 1: grpcserver.v1.FilterProto
	(*ReadColumnProto)(nil),     // 2: grpcserver.v1.ReadColumnProto
	(*PKReadRequestProto)(nil),  // 3: grpcserver.v1.PKReadRequestProto
	(*ColumnValueProto)(nil),    // 4: grpcserver.v1.ColumnValueProto
	(*PKReadResponseProto)(nil), // 5: grpcserver.v1.PKReadResponseProto
	(*BatchRequestProto)(nil),   // 6: grpcserver.v1.BatchRequestProto
	(*BatchResponseProto)(nil),  // 7: grpcserver.v1.BatchResponseProto
	(*MemoryStatsProto)(nil),    // 8: grpcserver.v1.MemoryStatsProto
	(*RonDBStatsProto)(nil),     // 9: grpcserver.v1.RonDBStatsProto
	(*StatRequestProto)(nil),    // 10: grpcserver.v1.StatRequestProto
	(*StatResponseProto)(nil),   // 11: grpcserver.v1.StatResponseProto
	(*HealthRequestProto)(nil),  // 12: grpcserver.v1.HealthRequestProto
	(*HealthResponseProto)(nil), // 13: grpcserver.v1.HealthResponseProto
	nil,                         // 14: grpcserver.v1.PKReadResponseProto.DataEntry
}
var file_api_rdrs_proto_depIdxs = []int32{
	1,  // 0: grpcserver.v1.PKReadRequestProto.Filters:type_name -> grpcserver.v1.FilterProto
	2,  // 1: grpcserver.v1.PKReadRequestProto.ReadColumns:type_name -> grpcserver.v1.ReadColumnProto
	14, // 2: grpcserver.v1.PKReadResponseProto.Data:type_name -> grpcserver.v1.PKReadResponseProto.DataEntry
	3,  // 3: grpcserver.v1.BatchRequestProto.operations:type_name -> grpcserver.v1.PKReadRequestProto
	5,  // 4: grpcserver.v1.BatchResponseProto.responses:type_name -> grpcserver.v1.PKReadResponseProto
	8,  // 5: grpcserver.v1.StatResponseProto.MemoryStats:type_name -> grpcserver.v1.MemoryStatsProto
	9,  // 6: grpcserver.v1.StatResponseProto.RonDBStats:type_name -> grpcserver.v1.RonDBStatsProto
	4,  // 7: grpcserver.v1.PKReadResponseProto.DataEntry.value:type_name -> grpcserver.v1.ColumnValueProto
	0,  // 8: grpcserver.v1.RonDBREST.Ping:input_type -> grpcserver.v1.Empty
	3,  // 9: grpcserver.v1.RonDBREST.PKRead:input_type -> grpcserver.v1.PKReadRequestProto
	6,  // 10: grpcserver.v1.RonDBREST.Batch:input_type -> grpcserver.v1.BatchRequestProto
	10, // 11: grpcserver.v1.RonDBREST.Stat:input_type -> grpcserver.v1.StatRequestProto
	12, // 12: grpcserver.v1.RonDBREST.Health:input_type -> grpcserver.v1.HealthRequestProto
	0,  // 13: grpcserver.v1.RonDBREST.Ping:output_type -> grpcserver.v1.Empty
	5,  // 14: grpcserver.v1.RonDBREST.PKRead:output_type -> grpcserver.v1.PKReadResponseProto
	7,  // 15: grpcserver.v1.RonDBREST.Batch:output_type -> grpcserver.v1.BatchResponseProto
	11, // 16: grpcserver.v1.RonDBREST.Stat:output_type -> grpcserver.v1.StatResponseProto
	13, // 17: grpcserver.v1.RonDBREST.Health:output_type -> grpcserver.v1.HealthResponseProto
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_rdrs_proto_init() }
func file_api_rdrs_proto_init() {
	if File_api_rdrs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_rdrs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadColumnProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PKReadRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnValueProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PKReadResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemoryStatsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RonDBStatsProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthRequestProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rdrs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponseProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_rdrs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rdrs_proto_goTypes,
		DependencyIndexes: file_api_rdrs_proto_depIdxs,
		MessageInfos:      file_api_rdrs_proto_msgTypes,
	}.Build()
	File_api_rdrs_proto = out.File
	file_api_rdrs_proto_rawDesc = nil
	file_api_rdrs_proto_goTypes = nil
	file_api_rdrs_proto_depIdxs = nil
}
