/*
   Copyright (c) 2026, 2026, Hopsworks and/or its affiliates.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is designed to work with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have either included with
   the program or referenced in the documentation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
*/

package data

import (
	"fmt"
	"strings"

	"github.com/logicalclocks/rondb/tools/rondb-cli/internal/fsq/ddl"
)

// MTROptions controls the MTR include rendering.
type MTROptions struct {
	DB         string // database the tables are created in (MTR: "test")
	Scale      Scale
	HashTwin   bool
	TargetRows int // rows per INSERT statement (default 4000)
	// MaxEntities bounds the _seq helper (the include is for small scales).
	MaxEntities int64
}

func (o *MTROptions) defaults() {
	if o.DB == "" {
		o.DB = "test"
	}
	if o.TargetRows <= 0 {
		o.TargetRows = 4000
	}
	if o.MaxEntities <= 0 {
		o.MaxEntities = 100000
	}
}

const mtrHeader = `# Generated by rondb-cli ".fs_emit_mtr" (RONDB-1121 feature-store RonSQL
# test framework) -- do not edit by hand; regenerate with
#   rondb --no-mysql --no-rdrs --no-rondis -e ".fs_emit_mtr <dir> --sf %g --db %s"
# Data model: storage/ndb/claude_files/fs_ronsql/data_model.md
`

// RenderSchemaInc renders include/fs_schema.inc: the database and every
// feature-group table, created with the exact Hopsworks online DDL.
func RenderSchemaInc(o MTROptions) (string, error) {
	o.defaults()
	var b strings.Builder
	fmt.Fprintf(&b, mtrHeader, o.Scale.SF, o.DB)
	b.WriteString("#\n# fs_schema.inc: create the feature-group tables (Hopsworks online DDL).\n")
	b.WriteString("--disable_query_log\n--disable_warnings\n")
	b.WriteString(ddl.CreateDatabase(o.DB) + "\n")
	for _, t := range Tables() {
		if t.HashTwin && !o.HashTwin {
			continue
		}
		stmt, err := ddl.BuildCreateStatement(o.DB, t.FG)
		if err != nil {
			return "", fmt.Errorf("%s: %w", t.Table, err)
		}
		b.WriteString(stmt + ";\n")
	}
	b.WriteString("--enable_warnings\n--enable_query_log\n")
	return b.String(), nil
}

// RenderDropInc renders include/fs_drop.inc.
func RenderDropInc(o MTROptions) string {
	o.defaults()
	var b strings.Builder
	fmt.Fprintf(&b, mtrHeader, o.Scale.SF, o.DB)
	b.WriteString("#\n# fs_drop.inc: drop the feature-group tables.\n")
	b.WriteString("--disable_query_log\n--disable_warnings\n")
	tables := Tables()
	for i := len(tables) - 1; i >= 0; i-- {
		b.WriteString(ddl.DropTable(o.DB, tables[i].FG) + "\n")
	}
	b.WriteString("--enable_warnings\n--enable_query_log\n")
	return b.String()
}

// seqDigits returns how many digit tables the _seq helper needs for n rows.
func seqDigits(n int64) int {
	d, limit := 1, int64(10)
	for limit < n {
		d++
		limit *= 10
	}
	return d
}

// RenderDataInc renders include/fs_data.inc: the deterministic load through
// MEMORY helper tables and INSERT ... SELECT, chunked so no statement
// inserts more than TargetRows rows, followed by the checksum assertions.
func RenderDataInc(o MTROptions) (string, error) {
	o.defaults()
	sc := o.Scale
	maxEnt := sc.E
	for _, n := range []int64{sc.M, sc.A, RegionCount, CountryCount} {
		if n > maxEnt {
			maxEnt = n
		}
	}
	if maxEnt > o.MaxEntities {
		return "", fmt.Errorf("scale factor %g needs %d entities; the MTR include supports at most %d (use .fs_load)",
			sc.SF, maxEnt, o.MaxEntities)
	}
	var b strings.Builder
	fmt.Fprintf(&b, mtrHeader, sc.SF, o.DB)
	fmt.Fprintf(&b, "#\n# fs_data.inc: deterministic load at scale factor %g (E=%d customers,\n"+
		"# M=%d merchants, A=%d accounts).  Every value is computed server-side from\n"+
		"# the row coordinates; no RAND.  TIMESTAMP literals are stored in UTC.\n", sc.SF, sc.E, sc.M, sc.A)
	b.WriteString("--disable_query_log\n--disable_warnings\n")
	b.WriteString("SET time_zone = '+00:00';\n\n")

	// Helper tables.
	b.WriteString("CREATE TABLE _d (d INT) ENGINE=MEMORY;\n")
	b.WriteString("INSERT INTO _d VALUES (0),(1),(2),(3),(4),(5),(6),(7),(8),(9);\n")
	digits := seqDigits(maxEnt)
	var terms, froms []string
	for i := 0; i < digits; i++ {
		alias := fmt.Sprintf("d%d", i)
		mult := int64(1)
		for j := 0; j < digits-1-i; j++ {
			mult *= 10
		}
		if mult == 1 {
			terms = append(terms, alias+".d")
		} else {
			terms = append(terms, fmt.Sprintf("%s.d*%d", alias, mult))
		}
		froms = append(froms, "_d "+alias)
	}
	b.WriteString("CREATE TABLE _seq (n INT NOT NULL PRIMARY KEY) ENGINE=MEMORY;\n")
	fmt.Fprintf(&b, "INSERT INTO _seq SELECT %s + 1 FROM %s;\n", strings.Join(terms, " + "), strings.Join(froms, ", "))
	fmt.Fprintf(&b, "CREATE TABLE _seq300 (n INT NOT NULL PRIMARY KEY) ENGINE=MEMORY;\n")
	fmt.Fprintf(&b, "INSERT INTO _seq300 SELECT n FROM _seq WHERE n <= %d;\n", MaxRowsPerEntity)
	classTable := func(name string, vals []int) {
		fmt.Fprintf(&b, "CREATE TABLE %s (k INT NOT NULL PRIMARY KEY, n INT NOT NULL) ENGINE=MEMORY;\n", name)
		var rows []string
		for k, v := range vals {
			rows = append(rows, fmt.Sprintf("(%d,%d)", k, v))
		}
		fmt.Fprintf(&b, "INSERT INTO %s VALUES %s;\n", name, strings.Join(rows, ","))
	}
	classTable("_ntx", NTxClass[:])
	classTable("_nsess", NSessClass[:])
	classTable("_nbal", NBalClass[:])
	b.WriteString("CREATE TABLE _spacing (k INT NOT NULL PRIMARY KEY, s BIGINT NOT NULL) ENGINE=MEMORY;\n")
	fmt.Fprintf(&b, "INSERT INTO _spacing VALUES (0,%d),(1,%d),(2,%d),(3,%d);\n",
		SpacingSeconds[0], SpacingSeconds[1], SpacingSeconds[2], SpacingSeconds[3])
	b.WriteString("CREATE TABLE _offset (k INT NOT NULL PRIMARY KEY, o BIGINT NOT NULL) ENGINE=MEMORY;\n")
	fmt.Fprintf(&b, "INSERT INTO _offset VALUES (0,%d),(1,%d),(2,%d);\n\n",
		OffsetSeconds[0], OffsetSeconds[1], OffsetSeconds[2])

	// Tables, chunked.
	for _, t := range Tables() {
		if t.HashTwin && !o.HashTwin {
			continue
		}
		n := t.Entities(sc)
		chunk := t.ChunkEntities(o.TargetRows)
		fmt.Fprintf(&b, "# --- %s: %d entities, ~%g rows each, %d entities per statement ---\n",
			t.Table, n, t.Mean, chunk)
		for lo := int64(1); lo <= n; lo += chunk {
			hi := lo + chunk - 1
			if hi > n {
				hi = n
			}
			fmt.Fprintf(&b, "INSERT INTO `%s`.`%s` %s\n%s;\n", o.DB, t.Table, t.ColumnList(), t.Select(sc, o.DB, lo, hi))
		}
		b.WriteString("\n")
	}

	b.WriteString("DROP TABLE _d, _seq, _seq300, _ntx, _nsess, _nbal, _spacing, _offset;\n\n")

	// Checksums: the include dies at record time when a table differs from
	// the Go formulas, so the MTR data can never silently drift.
	b.WriteString("# --- checksums (computed by the Go formulas at emit time) ---\n")
	for _, c := range Checksums(sc, o.HashTwin) {
		// No nested backticks: mysqltest evaluates the text between the
		// first and the last backtick of a --let value as a query.
		sum, cnt := "0", "0"
		if c.SumExpr != "" {
			sum = "SUM(" + c.SumExpr + ")"
		}
		if c.CntExpr != "" {
			cnt = "COUNT(" + c.CntExpr + ")"
		}
		fmt.Fprintf(&b, "--let $fs_check = `SELECT CONCAT_WS(',', COUNT(*), %s, %s) FROM %s.%s`\n",
			sum, cnt, o.DB, c.Table)
		fmt.Fprintf(&b, "if ($fs_check != '%d,%d,%d')\n{\n  --die %s checksum mismatch: expected %d,%d,%d got $fs_check\n}\n",
			c.Count, c.Sum, c.CntValue, c.Table, c.Count, c.Sum, c.CntValue)
	}
	b.WriteString("--enable_warnings\n--enable_query_log\n")
	return b.String(), nil
}

// RenderSchemaSQL renders the plain DDL script (database + tables) for
// humans and for .fs_schema.
func RenderSchemaSQL(db string, hashTwin bool) (string, error) {
	var b strings.Builder
	b.WriteString(ddl.CreateDatabase(db) + "\n")
	for _, t := range Tables() {
		if t.HashTwin && !hashTwin {
			continue
		}
		stmt, err := ddl.BuildCreateStatement(db, t.FG)
		if err != nil {
			return "", err
		}
		b.WriteString(stmt + ";\n")
	}
	return b.String(), nil
}
