image: Visual Studio 2022
version: '{build}'
platform: x64

skip_branch_with_pr: true

before_build:
- cmake -H. -Bbuild

build_script:
- if "%APPVEYOR_REPO_TAG%"=="true" (set CONFIGURATION=RelWithDebInfo) else (set CONFIGURATION=Debug)
- cmake --build build --config "%CONFIGURATION%"

# TODO enable CMocka tests, maybe package the binaries
