name: Lint source code

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  unix:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout Trantor source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: (Linux) Install dependencies
        run: |
          # Installing packages might fail as the github image becomes outdated
          sudo apt update
          sudo apt install dos2unix clang-format
          pip install cmake-format

      - name: Lint
        run: ./format.sh && git diff --exit-code
