/*
   Copyright (c) 2026, 2026, Hopsworks and/or its affiliates.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is designed to work with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have either included with
   the program or referenced in the documentation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
*/

package fuzz

// Hazards (random_generator.md §5.4): shapes with an OPEN HANG or CRASH row
// in mysql-test/suite/ronsql_cte/findings/_discovery_log.md, translated
// from the TPC-H schema to the feature-store schema.  They are never
// generated by default; `.fs_fuzz envelope --include-hazards` runs them
// single-threaded with a short timeout and a crash probe after each.

// Hazard is one discovery-log row translated to the feature-store schema.
type Hazard struct {
	ID      string // discovery-log id, e.g. "D18"
	Class   string // HANG | CRASH | ERROR
	Summary string
	SQL     string
	Ordered bool
}

// Hazards lists the translations of the open rows; the unit test checks
// that every open HANG / CRASH row of the discovery log has one.  Empty
// since 2026-10-06: every row was fixed (RONDB-1072, RONDB-1107) and its
// translation moved to FormerHazards.
var Hazards = []Hazard{}

// FormerHazard is the translation of a fixed hazard row, run by the
// regular `former-hazard` production: compared with MySQL, or, when the
// fix was a clean rejection, tagged with the expectation-table construct
// of that rejection.
type FormerHazard struct {
	ID        string
	Summary   string
	SQL       string
	Construct string // expectation construct of the fix's rejection, or ""
}

// FormerHazards are the translations of the fixed hazard rows (their TPC-H
// shapes run green in ronsql_cte: agg-03, filter-12 / -13, J14 / J15 / J18,
// agg-06 / -19 / -20, agg-11..15, MM17; J16 / J17 pin D5's rejection).
var FormerHazards = []FormerHazard{
	{"D3", "projection-only main SELECT over a CTE_LOOKUP child (no main aggregation)",
		"WITH `ord` AS (SELECT `customer_id` AS `k`, COUNT(*) AS `n`, MIN(`amount`) AS `mn` FROM `transactions_1` WHERE `customer_id` IN (1, 2, 3, 4, 5) GROUP BY `customer_id`) " +
			"SELECT `ord`.`k` AS `k`, `ord`.`n` AS `n`, `ord`.`mn` AS `mn` FROM `customers_1` AS `c` JOIN `ord` ON `ord`.`k` = `c`.`customer_id`;", ""},
	// The hang was a stale-binary artifact; column-vs-column in a CTE body
	// runs for columns of identical type since RONDB-1107 (fee and
	// merchant_id are both INT; the translation's original fee < amount
	// mixes INT and BIGINT and is the colcol-mixed-type probe).
	{"D4", "CTE-body col-vs-col WHERE (non-indexed left) feeding a parent-GROUP-BY main aggregate",
		"WITH `liq` AS (SELECT `merchant_id` AS `k`, COUNT(*) AS `n`, SUM(`amount`) AS `q` FROM `transactions_1` WHERE `fee` < `merchant_id` GROUP BY `merchant_id`) " +
			"SELECT `m`.`mcc` AS `mcc`, SUM(`liq`.`n`) AS `n`, SUM(`liq`.`q`) AS `q` FROM `merchants_1` AS `m` JOIN `liq` ON `liq`.`k` = `m`.`merchant_id` GROUP BY `m`.`mcc`;", ""},
	// It crashed RDRS; since ea50c8a56e3 a fan-out aggregation across a
	// non-ancestor sibling is rejected at prepare time.
	{"D5", "3-table INNER chain: real parent JOIN CTE_LOOKUP child JOIN real-table child",
		"WITH `cust` AS (SELECT `customer_id` AS `k`, COUNT(*) AS `n` FROM `transactions_1` GROUP BY `customer_id`) " +
			"SELECT `r`.`region_name` AS `region_name`, SUM(`cust`.`n`) AS `n` FROM `customers_1` AS `c` JOIN `cust` ON `cust`.`k` = `c`.`customer_id` " +
			"JOIN `regions_1` AS `r` ON `r`.`region_id` = `c`.`region_id` GROUP BY `r`.`region_name`;", "fanout-sibling"},
	{"D6", "scalar aggregate over a high-cardinality-key CTE looked up under a large root scan",
		"WITH `t` AS (SELECT `event_time` AS `k`, COUNT(*) AS `n` FROM `transactions_1` GROUP BY `event_time`) " +
			"SELECT MAX(`t`.`n`) AS `mx`, COUNT(*) AS `c` FROM `transactions_1` AS `x` JOIN `t` ON `t`.`k` = `x`.`event_time`;", ""},
	{"D12", "CTE-body col-vs-col WHERE (indexed left) feeding an aggregating main",
		"WITH `sums` AS (SELECT `customer_id` AS `k`, COUNT(*) AS `n` FROM `transactions_1` WHERE `customer_id` < `amount` GROUP BY `customer_id`) " +
			"SELECT `sums`.`k` AS `k`, SUM(`sums`.`n`) AS `n` FROM `customers_1` AS `c` JOIN `sums` ON `sums`.`k` = `c`.`customer_id` GROUP BY `sums`.`k`;", ""},
	// Over tier, not category: category holds collation-equal variants
	// (travel / Travel), whose MIN / MAX representative is unspecified (the
	// F8 rule; the category form gave MySQL Travel, RonSQL travel).
	{"D18", "main query re-aggregates a string MIN/MAX CTE output",
		"WITH `ord` AS (SELECT `customer_id` AS `k`, MIN(`tier`) AS `mn`, MAX(`tier`) AS `mx`, COUNT(*) AS `n` FROM `customers_1` GROUP BY `customer_id`) " +
			"SELECT MIN(`ord`.`mn`) AS `mn`, MAX(`ord`.`mx`) AS `mx`, SUM(`ord`.`n`) AS `n` FROM `customers_1` AS `c` JOIN `ord` ON `ord`.`k` = `c`.`customer_id`;", ""},
	{"D19", "real table JOIN CTE with a main-query WHERE on a parent column",
		"WITH `cust` AS (SELECT `customer_id` AS `k`, SUM(`amount`) AS `t` FROM `transactions_1` GROUP BY `customer_id`) " +
			"SELECT `cust`.`k` AS `k`, SUM(`cust`.`t`) AS `t` FROM `customers_1` AS `c` JOIN `cust` ON `cust`.`k` = `c`.`customer_id` WHERE `c`.`region_id` = 5 GROUP BY `cust`.`k`;", ""},
	{"D20", "multi-key CTE complete-key lookup with the join predicates in reversed order",
		"WITH `x` AS (SELECT `account_id` AS `k1`, `currency` AS `k2`, COUNT(*) AS `n` FROM `balance_hist_1` GROUP BY `account_id`, `currency`) " +
			"SELECT `b`.`account_id` AS `account_id`, SUM(`x`.`n`) AS `n` FROM `balances_1` AS `b` JOIN `x` ON `x`.`k2` = `b`.`currency` AND `x`.`k1` = `b`.`account_id` GROUP BY `b`.`account_id`;", ""},
	{"D23", "projection-only main SELECT with a joined CTE_LOOKUP child that has no selected columns",
		"WITH `cust` AS (SELECT `customer_id` AS `k`, SUM(`amount`) AS `t` FROM `transactions_1` GROUP BY `customer_id`) " +
			"SELECT `c`.`customer_id` AS `customer_id` FROM `customers_1` AS `c` JOIN `cust` ON `cust`.`k` = `c`.`customer_id` WHERE `c`.`customer_id` <= 20;", ""},
}

// HazardCases renders the hazards as envelope cases of a run.
func HazardCases(seed uint64) []EnvCase {
	out := make([]EnvCase, 0, len(Hazards))
	for i, h := range Hazards {
		out = append(out, EnvCase{ID: EnvVersion + "-hazard-" + h.ID, Seed: seed, Index: -1 - i, Production: "hazard",
			SQL: h.SQL, Ordered: h.Ordered, Constructs: []string{"hazard-" + h.ID}, Signature: "hazard|" + h.ID, Hazard: h.ID})
	}
	return out
}
