/*
   Copyright (c) 2026, 2026, Hopsworks and/or its affiliates.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is designed to work with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have either included with
   the program or referenced in the documentation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
*/

package fuzz

// Hazards (random_generator.md §5.4): shapes with a recorded HANG or CRASH
// in mysql-test/suite/ronsql_cte/findings/_discovery_log.md, translated
// from the TPC-H schema to the feature-store schema.  They are never
// generated by default; `.fs_fuzz envelope --include-hazards` runs them
// single-threaded with a short timeout and a crash probe after each.

// Hazard is one discovery-log row translated to the feature-store schema.
type Hazard struct {
	ID      string // discovery-log id, e.g. "D18"
	Class   string // HANG | CRASH | ERROR
	Summary string
	SQL     string
	Ordered bool
}

// Hazards lists the translations; the unit test checks that every open
// HANG / CRASH row of the discovery log has one.
var Hazards = []Hazard{
	{"F15", "CRASH", "aggregating main LEFT JOINs a CTE_LOOKUP whose key misses (null row into the join-aggregation leaf, DbspjMain.cpp:15201)",
		"WITH `tx` AS (SELECT `customer_id` AS `k`, COUNT(*) AS `n`, SUM(`amount`) AS `s` FROM `transactions_1` WHERE `customer_id` IN (1012, 644, 91, 172, 486, 400, 1467, 880, 338, 1829) GROUP BY `customer_id`), " +
			"`se` AS (SELECT `customer_id` AS `k`, COUNT(*) AS `n`, SUM(`duration`) AS `s` FROM `sessions_1` WHERE `customer_id` IN (1012, 644, 91, 172, 486, 400, 1467, 880, 338, 1829) GROUP BY `customer_id`) " +
			"SELECT `c`.`customer_id` AS `customer_id`, MAX(`tx`.`n`) AS `tx_n`, SUM(`tx`.`s`) AS `tx_s`, MAX(`se`.`n`) AS `se_n`, SUM(`se`.`s`) AS `se_s` " +
			"FROM `customers_1` AS `c` LEFT JOIN `tx` ON `tx`.`k` = `c`.`customer_id` LEFT JOIN `se` ON `se`.`k` = `c`.`customer_id` GROUP BY `c`.`customer_id`;", false},
	{"D3", "HANG", "projection-only main SELECT over a CTE_LOOKUP child (no main aggregation)",
		"WITH `ord` AS (SELECT `customer_id` AS `k`, COUNT(*) AS `n`, MIN(`amount`) AS `mn` FROM `transactions_1` WHERE `customer_id` IN (1, 2, 3, 4, 5) GROUP BY `customer_id`) " +
			"SELECT `ord`.`k` AS `k`, `ord`.`n` AS `n`, `ord`.`mn` AS `mn` FROM `customers_1` AS `c` JOIN `ord` ON `ord`.`k` = `c`.`customer_id`;", false},
	{"D4", "HANG", "CTE-body signed-int col-vs-col WHERE feeding a parent-GROUP-BY main aggregate",
		"WITH `liq` AS (SELECT `merchant_id` AS `k`, COUNT(*) AS `n`, SUM(`amount`) AS `q` FROM `transactions_1` WHERE `fee` < `amount` GROUP BY `merchant_id`) " +
			"SELECT `m`.`mcc` AS `mcc`, SUM(`liq`.`n`) AS `n`, SUM(`liq`.`q`) AS `q` FROM `merchants_1` AS `m` JOIN `liq` ON `liq`.`k` = `m`.`merchant_id` GROUP BY `m`.`mcc`;", false},
	{"D5", "HANG", "3-table INNER chain: real parent JOIN CTE_LOOKUP child JOIN real-table child",
		"WITH `cust` AS (SELECT `customer_id` AS `k`, COUNT(*) AS `n` FROM `transactions_1` GROUP BY `customer_id`) " +
			"SELECT `r`.`region_name` AS `region_name`, SUM(`cust`.`n`) AS `n` FROM `customers_1` AS `c` JOIN `cust` ON `cust`.`k` = `c`.`customer_id` " +
			"JOIN `regions_1` AS `r` ON `r`.`region_id` = `c`.`region_id` GROUP BY `r`.`region_name`;", false},
	{"D6", "CRASH", "scalar aggregate over a high-cardinality-key CTE looked up under a large root scan",
		"WITH `t` AS (SELECT `event_time` AS `k`, COUNT(*) AS `n` FROM `transactions_1` GROUP BY `event_time`) " +
			"SELECT MAX(`t`.`n`) AS `mx`, COUNT(*) AS `c` FROM `transactions_1` AS `x` JOIN `t` ON `t`.`k` = `x`.`event_time`;", false},
	{"D12", "ERROR", "CTE-body signed-int col-vs-col WHERE feeding an aggregating main (RonSQLRetryableError)",
		"WITH `sums` AS (SELECT `customer_id` AS `k`, COUNT(*) AS `n` FROM `transactions_1` WHERE `customer_id` < `amount` GROUP BY `customer_id`) " +
			"SELECT `sums`.`k` AS `k`, SUM(`sums`.`n`) AS `n` FROM `customers_1` AS `c` JOIN `sums` ON `sums`.`k` = `c`.`customer_id` GROUP BY `sums`.`k`;", false},
	{"D18", "CRASH", "main query re-aggregates a string MIN/MAX CTE output (data node crash)",
		"WITH `ord` AS (SELECT `customer_id` AS `k`, MIN(`category`) AS `mn`, MAX(`category`) AS `mx`, COUNT(*) AS `n` FROM `transactions_1` GROUP BY `customer_id`) " +
			"SELECT MIN(`ord`.`mn`) AS `mn`, MAX(`ord`.`mx`) AS `mx`, SUM(`ord`.`n`) AS `n` FROM `customers_1` AS `c` JOIN `ord` ON `ord`.`k` = `c`.`customer_id`;", false},
	{"D19", "HANG", "real table JOIN CTE with a main-query WHERE on a parent column",
		"WITH `cust` AS (SELECT `customer_id` AS `k`, SUM(`amount`) AS `t` FROM `transactions_1` GROUP BY `customer_id`) " +
			"SELECT `cust`.`k` AS `k`, SUM(`cust`.`t`) AS `t` FROM `customers_1` AS `c` JOIN `cust` ON `cust`.`k` = `c`.`customer_id` WHERE `c`.`region_id` = 5 GROUP BY `cust`.`k`;", false},
	{"D20", "HANG", "multi-key CTE complete-key lookup with the join predicates in reversed order",
		"WITH `x` AS (SELECT `account_id` AS `k1`, `currency` AS `k2`, COUNT(*) AS `n` FROM `balance_hist_1` GROUP BY `account_id`, `currency`) " +
			"SELECT `b`.`account_id` AS `account_id`, SUM(`x`.`n`) AS `n` FROM `balances_1` AS `b` JOIN `x` ON `x`.`k2` = `b`.`currency` AND `x`.`k1` = `b`.`account_id` GROUP BY `b`.`account_id`;", false},
	{"D23", "CRASH", "projection-only main SELECT with a joined CTE_LOOKUP child that has no selected columns (data node SIGSEGV)",
		"WITH `cust` AS (SELECT `customer_id` AS `k`, SUM(`amount`) AS `t` FROM `transactions_1` GROUP BY `customer_id`) " +
			"SELECT `c`.`customer_id` AS `customer_id` FROM `customers_1` AS `c` JOIN `cust` ON `cust`.`k` = `c`.`customer_id` WHERE `c`.`customer_id` <= 20;", false},
}

// HazardCases renders the hazards as envelope cases of a run.
func HazardCases(seed uint64) []EnvCase {
	out := make([]EnvCase, 0, len(Hazards))
	for i, h := range Hazards {
		out = append(out, EnvCase{ID: EnvVersion + "-hazard-" + h.ID, Seed: seed, Index: -1 - i, Production: "hazard",
			SQL: h.SQL, Ordered: h.Ordered, Constructs: []string{"hazard-" + h.ID}, Signature: "hazard|" + h.ID, Hazard: h.ID})
	}
	return out
}
