matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode12.2

sudo: required

language: cpp

addons:
  apt:
    sources:
    - xenial
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main'
    - sourceline: 'ppa:mhier/libboost-latest'
    packages:
    - gcc
    - g++
    - libjsoncpp-dev
    - uuid-dev
    - zlib1g-dev
    - postgresql-server-dev-10
    - openssl
    - libssl-dev
    - libsqlite3-dev
    - mariadb-client
    - mariadb-server
    - build-essential
    - cmake
    - boost1.67
    - libbrotli-dev
  homebrew:
    packages:
    - jsoncpp
    - ossp-uuid
    - openssl
    - cmake
    - libtool
    - lz4
    - mariadb
    - sqlite3
    update: true
  mariadb: '10.0'

before_install:
  - wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - tar xf release-1.10.0.tar.gz
  - cd googletest-release-1.10.0
  - cmake .
  - make
  - sudo make install
  - cd -

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
       brew tap homebrew/services;
       brew services restart postgresql;
       brew services start mariadb;
       sleep 4;
       mariadb -e "CREATE USER 'root'@'localhost' IDENTIFIED BY ''";
       mariadb -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('')";
       mariadb -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost'";
       mariadb -e "FLUSH PRIVILEGES";
       brew services restart mariadb;
       sleep 4;
       psql -c 'create user postgres superuser;' postgres;
    fi

services:
  - postgresql
  - mysql

script:
  - ./build.sh -t
  - ./test.sh -t
  - sudo rm /usr/local/lib/libtrantor.a && sudo rm /usr/local/lib/libdrogon.a
  - ./build.sh -tshared
  - ./test.sh -t
