/*
   Copyright (c) 2026, 2026, Hopsworks and/or its affiliates.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is designed to work with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have either included with
   the program or referenced in the documentation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
*/

// Package mtr renders MTR test files from the case matrix so the golden
// regression needs no Go at run time: every case becomes a
// ronsql_compare.inc block (strict unless the outcome is a known wrong
// result), a known rejection becomes a ronsql_cli rejection assert, and
// a hazard is written out as a comment.
package mtr

import (
	"fmt"
	"strings"

	"github.com/logicalclocks/rondb/tools/rondb-cli/internal/fsq/cases"
)

const header = `# ronsql_fs_templates — generated by rondb-cli ".fs_emit_mtr --cases"
# (RONDB-1121 feature-store RonSQL test framework); do not edit by hand.
# Every Hopsworks serving shape of storage/ndb/claude_files/fs_ronsql/
# shape_catalog.md, emitted by the Go port of PreparedStatementBuilder,
# bound to keys of the deterministic data set, and compared between the
# mysql client and RonSQL via suite/ronsql/include/ronsql_compare.inc.
# Known engine rejections are asserted through ronsql_cli; known wrong
# results are recorded non-strictly; hazards (crashes) are commented out.
# Statements with AVG or DECIMAL/DOUBLE/FLOAT values compare with trailing
# fractional zeros stripped on both sides (formatting findings F2/F3).
# Findings: suite/ronsql_fs/findings/smoke.md.

--source include/have_ndb.inc

--disable_warnings
call mtr.add_suppression("Schema dist coordinator detected timeout");
call mtr.add_suppression("Participant timeout");
--enable_warnings

--let $suppress_ronsql_cli=yes

--echo === Create and load the feature-store data set ===
--source suite/ronsql_fs/include/fs_schema.inc
--source suite/ronsql_fs/include/fs_data.inc

DELIMITER |;
`

const footer = `
DELIMITER ;|

--echo
--echo === Cleanup ===
--source suite/ronsql_fs/include/fs_drop.inc
`

// numericCanon is the ronsql_compare.inc sed hook for cases.CanonNumeric:
// "68.6250" -> "68.625", "10.50" -> "10.5", "0.00" -> "0" on both sides
// (mysqltest keeps "\t" for sed and turns "\$" into "$").
const numericCanon = "# numeric canonicalization (F2/F3): trailing fractional zeros stripped on both sides\n" +
	"--let $canonicalization_script=s/(\\.[0-9]*[1-9])0+(\\t|\\$)/\\1\\2/g;s/\\.0+(\\t|\\$)/\\1/g\n"

func fileID(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

// RenderTemplatesTest renders t/ronsql_fs_templates.test.
func RenderTemplatesTest(cs []cases.Case, db string) string {
	var b strings.Builder
	b.WriteString(header)
	for _, c := range cs {
		if !c.MTR {
			continue
		}
		b.WriteString("\n--echo\n")
		fmt.Fprintf(&b, "--echo === %s: %s %s — %s ===\n", c.ID, c.Shape, c.Mode, strings.ReplaceAll(c.Note, "\n", " "))
		if c.Hazard != "" {
			fmt.Fprintf(&b, "# HAZARD %s: this statement crashed RDRS or a data node; not executed.\n", c.Hazard)
			for _, st := range c.Statements {
				fmt.Fprintf(&b, "#   %s\n", st.RonSQL)
			}
			continue
		}
		for i, st := range c.Statements {
			qf := fmt.Sprintf("$MYSQL_TMP_DIR/q_%s_%d.sql", fileID(c.ID), i)
			fmt.Fprintf(&b, "--let QUERY_FILE=%s\n--write_file $QUERY_FILE\n%s\nEOF\n", qf, st.RonSQL)
			if c.ExpectReject != nil {
				out := fmt.Sprintf("$MYSQL_TMP_DIR/rej_%s_%d.out", fileID(c.ID), i)
				fmt.Fprintf(&b, "# expected clean rejection (%s): %s\n", c.ExpectReject.Finding, c.ExpectReject.Pattern)
				fmt.Fprintf(&b, "--error 1\n--exec $RONSQL_CLI_EXE --connect-string $NDB_CONNECTSTRING -D %s --execute-file $QUERY_FILE > %s 2>&1\n", db, out)
				fmt.Fprintf(&b, "--exec grep -qF '%s' %s\n--remove_file %s\n--remove_file $QUERY_FILE\n", c.ExpectReject.Pattern, out, out)
				continue
			}
			if c.KnownWrong != nil {
				fmt.Fprintf(&b, "# known wrong result (%s): %s — recorded, not asserted\n--let $strict_diff=\n", c.KnownWrong.Finding, c.KnownWrong.Pattern)
			} else {
				b.WriteString("--let $strict_diff=yes\n")
			}
			if c.Ordered {
				b.WriteString("--let $skip_sort=yes\n")
			}
			if c.Canon == cases.CanonNumeric {
				b.WriteString(numericCanon)
			}
			b.WriteString("--source suite/ronsql/include/ronsql_compare.inc\n")
			b.WriteString("--echo == Expected result ==\n")
			if !c.Ordered {
				b.WriteString("--sorted_result\n")
			}
			fmt.Fprintf(&b, "%s|\n", strings.TrimSuffix(strings.TrimSpace(st.RonSQL), ";"))
		}
	}
	b.WriteString(footer)
	return b.String()
}
