-- CHARSET=latin1 COLLATE=latin1_general_cs fails with "Incorrect string value: '\xE2\x94\x82   ...' for column 'plan' at row 1"
-- when Trino tries to insert an event.
CREATE TABLE IF NOT EXISTS `hopsworks`.`trino_queries`
(
    `query_id`                          varchar(255) NOT NULL,
    `transaction_id`                    varchar(255) DEFAULT NULL,
    `query`                             mediumtext   NOT NULL,
    `update_type`                       varchar(255) DEFAULT NULL,
    `prepared_query`                    mediumtext,
    `query_state`                       varchar(255) NOT NULL,
    `plan`                              mediumtext,
    `stage_info_json`                   mediumtext,
    `user`                              varchar(255) NOT NULL,
    `principal`                         varchar(255) DEFAULT NULL,
    `trace_token`                       varchar(255) DEFAULT NULL,
    `remote_client_address`             varchar(255) DEFAULT NULL,
    `user_agent`                        varchar(255) DEFAULT NULL,
    `client_info`                       mediumtext,
    `client_tags_json`                  mediumtext   NOT NULL,
    `source`                            varchar(255) DEFAULT NULL,
    `catalog`                           varchar(255) DEFAULT NULL,
    `schema`                            varchar(255) DEFAULT NULL,
    `resource_group_id`                 varchar(255) DEFAULT NULL,
    `session_properties_json`           mediumtext   NOT NULL,
    `server_address`                    varchar(255) NOT NULL,
    `server_version`                    varchar(255) NOT NULL,
    `environment`                       varchar(255) NOT NULL,
    `query_type`                        varchar(255) DEFAULT NULL,
    `inputs_json`                       mediumtext   NOT NULL,
    `output_json`                       mediumtext,
    `error_code`                        varchar(255) DEFAULT NULL,
    `error_type`                        varchar(255) DEFAULT NULL,
    `failure_type`                      varchar(255) DEFAULT NULL,
    `failure_message`                   mediumtext,
    `failure_task`                      varchar(255) DEFAULT NULL,
    `failure_host`                      varchar(255) DEFAULT NULL,
    `failures_json`                     mediumtext,
    `warnings_json`                     mediumtext   NOT NULL,
    `cpu_time_millis`                   bigint       NOT NULL,
    `failed_cpu_time_millis`            bigint       NOT NULL,
    `wall_time_millis`                  bigint       NOT NULL,
    `queued_time_millis`                bigint       NOT NULL,
    `scheduled_time_millis`             bigint       NOT NULL,
    `failed_scheduled_time_millis`      bigint       NOT NULL,
    `waiting_time_millis`               bigint       NOT NULL,
    `analysis_time_millis`              bigint       NOT NULL,
    `planning_time_millis`              bigint       NOT NULL,
    `planning_cpu_time_millis`          bigint       NOT NULL,
    `starting_time_millis`              bigint       NOT NULL,
    `execution_time_millis`             bigint       NOT NULL,
    `input_blocked_time_millis`         bigint       NOT NULL,
    `failed_input_blocked_time_millis`  bigint       NOT NULL,
    `output_blocked_time_millis`        bigint       NOT NULL,
    `failed_output_blocked_time_millis` bigint       NOT NULL,
    `physical_input_read_time_millis`   bigint       NOT NULL,
    `peak_memory_bytes`                 bigint       NOT NULL,
    `peak_task_memory_bytes`            bigint       NOT NULL,
    `physical_input_bytes`              bigint       NOT NULL,
    `physical_input_rows`               bigint       NOT NULL,
    `internal_network_bytes`            bigint       NOT NULL,
    `internal_network_rows`             bigint       NOT NULL,
    `total_bytes`                       bigint       NOT NULL,
    `total_rows`                        bigint       NOT NULL,
    `output_bytes`                      bigint       NOT NULL,
    `output_rows`                       bigint       NOT NULL,
    `written_bytes`                     bigint       NOT NULL,
    `written_rows`                      bigint       NOT NULL,
    `cumulative_memory`                 double       NOT NULL,
    `failed_cumulative_memory`          double       NOT NULL,
    `completed_splits`                  bigint       NOT NULL,
    `retry_policy`                      varchar(255) NOT NULL,
    `operator_summaries_json`           mediumtext   NOT NULL,
    PRIMARY KEY (`query_id`),
    KEY `idx_trino_queries_user` (`user`)
) ENGINE=ndbcluster DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
