-- Cluster-level config: name of the project whose materialised feature groups
-- are auto-imported into a user's project when they hit the wizard's
-- "import public dataset" action (see FeaturestoreService#importDefaults).
-- RDRS-P1-PORT: data-producing INSERT commented out. In this test pipeline the
-- migrations are DDL-only; the rows this statement produces are captured in
-- fixed/hopsworks-data/hopsworks_data.sql (dumped from a fully-migrated DB) and
-- would collide on re-seed.
-- INSERT INTO `hopsworks`.`variables` (`id`, `value`, `visibility`, `hide`)
-- VALUES ('default_featurestore_project_name', 'hopsworks_default', 0, 0)
-- ON DUPLICATE KEY UPDATE `id`=`id`;
