/*
   Copyright (c) 2026, 2026, Hopsworks and/or its affiliates.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License, version 2.0,
   as published by the Free Software Foundation.

   This program is designed to work with certain software (including
   but not limited to OpenSSL) that is licensed under separate terms,
   as designated in a particular file or component or in included license
   documentation.  The authors of MySQL hereby grant you an additional
   permission to link the program and your derivative works with the
   separately licensed software that they have either included with
   the program or referenced in the documentation.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License, version 2.0, for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA
*/

// Package emit is a port of the RonSQL template emitters of the Hopsworks
// online-serving builder,
// hopsworks-api/src/main/java/io/hops/hopsworks/api/featurestore/trainingdataset/PreparedStatementBuilder.java
// (HOPSWORKS_REF f85a653bc), method for method and append for append, so
// the Go output is byte-identical to the Java output on the golden
// fixtures (testdata/hopsworks_golden, generated by HopsworksGoldenDump).
//
// Ported: createServingPreparedStatementDTOS, collectSourceFeatures,
// aggregateSourceFeatures, aggregateOutputs, applyRonsqlAggregate,
// applyMysqlAggregate, aggregateOutputFeatureNames, buildDTO (RonSQL side
// and DTO fields), conjunctiveFilterConditions, renderRonsqlCondition,
// renderRonsqlLiteral, buildRonsqlCollectTemplate,
// createSnowflakePreparedStatementDTOS, constructSnowflakeJoinsDTO,
// buildRonsqlSnowflakeTemplates, buildSnowflakeStatement,
// validateExtractPrimaryFeatures, getSelectFeatures,
// getTrainingDatasetFeatures, NestedTrainingDatasetJoinTree, and the
// resolveCollectSources / parseStructFieldNames helpers of
// TrainingDatasetController.
//
// Not ported: Calcite (generateSQL / wrapOnlineCollect / wrapOnlineScan /
// getQuery rendering) — package mysqltwin re-renders that output in the
// observed text; persistence lookups, replaced by the spec.
package emit

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/logicalclocks/rondb/tools/rondb-cli/internal/fsq/mysqltwin"
	"github.com/logicalclocks/rondb/tools/rondb-cli/internal/fsq/spec"
)

// HopsworksRef is the Hopsworks commit the port mirrors.
const HopsworksRef = "f85a653bc"

const alias = "fg0" // PreparedStatementBuilder.ALIAS

var renderableConditions = map[spec.SqlCondition]bool{
	spec.CondEquals: true, spec.CondNotEquals: true, spec.CondGreaterThan: true,
	spec.CondGreaterThanOrEqual: true, spec.CondLessThan: true, spec.CondLessThanOrEqual: true,
	spec.CondLike: true,
}

var scanFilterConditions = map[spec.SqlCondition]bool{
	spec.CondEquals: true, spec.CondNotEquals: true, spec.CondGreaterThan: true,
	spec.CondGreaterThanOrEqual: true, spec.CondLessThan: true, spec.CondLessThanOrEqual: true,
}

var numericLiteral = regexp.MustCompile(`^-?\d+(\.\d+)?$`)

var numericTypePrefixes = []string{"tinyint", "smallint", "int", "bigint", "float", "double", "decimal"}

// feature mirrors io.hops.hopsworks.common.featurestore.query.Feature as
// the builder uses it: a feature-group column tagged with the join prefix.
type feature struct {
	Name         string
	Type         string
	Primary      bool
	DefaultValue *string
	OfflineOnly  bool
	Prefix       *string
	FGID         int
	// Alias is the Calcite table alias of the feature's join (nested queries).
	Alias string
}

// fgFeatures is the LinkedHashMap<String, Feature> of a join: declared order
// plus lookup by name.
type fgFeatures struct {
	list   []*feature
	byName map[string]*feature
}

func (m *fgFeatures) get(name string) *feature { return m.byName[name] }

// query mirrors the internal Query the builder hands to Calcite: the online
// database, the feature group and the selected features (nil entries are
// names that are not columns of the feature group, as in Java).
type query struct {
	project  string
	fg       spec.FeatureGroup
	features []*feature
	// nested is set for a snowflake subtree query (getQuery over childJoins).
	nested *nestedQuery
}

type nestedQuery struct {
	root  mysqltwin.Table
	joins []mysqltwin.JoinClause
}

func (q *query) table() string { return q.fg.TableName() }

type builder struct {
	v   *spec.View
	fgs map[int]spec.FeatureGroup
	opt spec.Options
}

// Build ports getServingStatements for a feature view (or a query-backed
// training dataset) and returns the ordered ServingPreparedStatementDTO
// list.  Hopsworks exceptions come back as *spec.GateError.
func Build(v *spec.View) ([]Statement, error) {
	if err := v.Normalize(); err != nil {
		return nil, err
	}
	b := &builder{v: v, fgs: v.FGMap(), opt: v.Options}
	if v.TrainingDataset {
		// build(uriInfo, resourceRequest, project, featurestore, id, batch):
		// no helper options on the training-dataset entry point.
		b.opt = spec.Options{Batch: v.Options.Batch}
	}
	joins := v.JoinsSorted()
	for _, j := range joins {
		if _, ok := b.fgs[j.FG]; !ok {
			return nil, spec.Gate(spec.CodeQueryFailedFGDeleted, "")
		}
	}
	snowflake := false
	for _, j := range joins {
		if j.Parent != 0 {
			snowflake = true
		}
	}
	if snowflake {
		return b.createSnowflakePreparedStatementDTOS(joins, len(v.Filters) > 0)
	}
	conds, isNil := conjunctiveFilterConditions(v.Filters)
	return b.createServingPreparedStatementDTOS(joins, conds, isNil)
}

// featuresOf builds the join's LinkedHashMap<String, Feature>.
func (b *builder) featuresOf(fg spec.FeatureGroup, prefix *string) *fgFeatures {
	m := &fgFeatures{byName: map[string]*feature{}}
	for _, c := range fg.Features {
		if _, dup := m.byName[c.Name]; dup {
			continue // toMap merge (a, b) -> a keeps the first
		}
		f := &feature{Name: c.Name, Type: c.Type, Primary: c.Primary, DefaultValue: c.DefaultValue,
			OfflineOnly: c.OfflineOnly, Prefix: prefix, FGID: fg.ID, Alias: alias}
		m.list = append(m.list, f)
		m.byName[c.Name] = f
	}
	return m
}

func primaryKeys(m *fgFeatures) []*feature {
	var pks []*feature
	for _, f := range m.list {
		if f.Primary {
			pks = append(pks, f)
		}
	}
	return pks
}

func containsFeature(list []*feature, f *feature) bool {
	for _, x := range list {
		if x != nil && f != nil && x.Name == f.Name && x.FGID == f.FGID {
			return true
		}
	}
	return false
}

func notOnlineEnabled(fg spec.FeatureGroup) error {
	return spec.Gate(spec.CodeFeaturestoreOnlineNotEnabled,
		"Inference vector is only available for training datasets generated by online enabled feature groups. Feature group `%s` is not online enabled.", fg.Name)
}

func primaryKeyRequired() error {
	return spec.Gate(spec.CodePrimaryKeyRequired,
		"Inference vector is only available for training datasets generated by feature groups with at least 1 primary key")
}

// ---- star schema (createServingPreparedStatementDTOS :226-352) -------------

type filterLeaf struct {
	feature   *feature
	condition spec.SqlCondition
	value     string
}

func (b *builder) createServingPreparedStatementDTOS(joins []spec.Join, filterConditions []spec.Filter, filtersNil bool) ([]Statement, error) {
	var out []Statement
	for _, join := range joins {
		fg := b.fgs[join.FG]
		if !fg.OnlineEnabled() {
			return nil, notOnlineEnabled(fg)
		}
		fgf := b.featuresOf(fg, join.Prefix)
		pks := primaryKeys(fgf)
		if len(pks) == 0 {
			return nil, primaryKeyRequired()
		}
		selectFeatures := getSelectFeatures(b.opt.Batch, b.opt.InferenceHelpers, join, fg, fgf, pks,
			b.opt.Logging, b.opt.VectorWithHelpers)
		if join.Aggregate != nil {
			selectFeatures = aggregateSourceFeatures(join.Aggregate, fgf, pks)
		}
		if join.CollectN != nil {
			selectFeatures = collectSourceFeatures(join, fg, fgf, pks)
		}
		if len(selectFeatures) == 0 {
			continue
		}
		q := &query{project: fg.OnlineDatabase(), fg: fg, features: selectFeatures}
		var collectOrderBy *feature
		if join.CollectN != nil && join.OrderBy != nil {
			collectOrderBy = fgf.get(*join.OrderBy)
		}
		excludedKey := ""
		if collectOrderBy != nil {
			excludedKey = *join.OrderBy
		} else if join.Aggregate != nil {
			excludedKey = fg.EventTime
		}
		var bindKeys []*feature
		for _, pk := range pks {
			if excludedKey == "" || pk.Name != excludedKey {
				bindKeys = append(bindKeys, pk)
			}
		}
		var extraFilters []filterLeaf
		var ronsqlExtraWhere strings.Builder
		var scanFilters []CollectFilter
		scanFilterable := true
		if join.CollectN != nil || join.Aggregate != nil {
			if filtersNil {
				return nil, spec.Gate(spec.CodeCollectUnsupportedOnlineFilt,
					"the feature view's filters contain OR, which cannot be applied to the online collect/aggregation statement for feature group %s", fg.Name)
			}
			for _, cond := range filterConditions {
				if _, ok := b.fgs[cond.FG]; !ok || cond.FG != fg.ID {
					continue
				}
				// review X7: a condition pinned to a join index applies to that join only
				if cond.JoinIndex != nil && *cond.JoinIndex != join.Index {
					continue
				}
				rendered, ok := renderRonsqlCondition(cond, fgf)
				if !ok {
					return nil, spec.Gate(spec.CodeCollectUnsupportedOnlineFilt,
						"the feature view's filter on '%s' cannot be applied to the online collect/aggregation statement for feature group %s", cond.Feature, fg.Name)
				}
				extraFilters = append(extraFilters, filterLeaf{feature: fgf.get(cond.Feature), condition: *cond.Condition, value: *cond.Value})
				ronsqlExtraWhere.WriteString(" AND " + rendered)
				if scanFilterConditions[*cond.Condition] {
					scanFilters = append(scanFilters, CollectFilter{Feature: cond.Feature, Condition: string(*cond.Condition),
						Value: *cond.Value, Type: fgf.get(cond.Feature).Type})
				} else {
					scanFilterable = false
				}
			}
		}
		dto, err := b.buildDTO(q, bindKeys, fg.ID, join.Index, b.opt.Batch, join.Prefix, join.CollectN, collectOrderBy,
			join.Ascending, extraFilters, ronsqlExtraWhere.String())
		if err != nil {
			return nil, err
		}
		if join.CollectN != nil && scanFilterable && len(scanFilters) > 0 {
			dto.CollectFilters = scanFilters
		}
		if err := applyRonsqlAggregate(&dto, join, fg, q, bindKeys, b.opt.Batch, ronsqlExtraWhere.String()); err != nil {
			return nil, err
		}
		applyMysqlAggregate(&dto, join, fg, q, bindKeys, b.opt.Batch, ronsqlExtraWhere.String())
		out = append(out, dto)
	}
	return out, nil
}

// getSelectFeatures :1249-1293.  Entries may be nil (a selected name that is
// not a feature-group column, e.g. an aggregate output), exactly like the
// Java list.
func getSelectFeatures(batch, inferenceHelperColumns bool, join spec.Join, fg spec.FeatureGroup, fgf *fgFeatures, pks []*feature,
	loggingMetaData, featureVectorWithInferenceHelpers bool) []*feature {
	var selected []*feature
	if inferenceHelperColumns {
		for _, tdf := range join.Features {
			if !tdf.InferenceHelper {
				continue
			}
			f := fgf.get(tdf.Name)
			if f == nil || !f.OfflineOnly {
				selected = append(selected, f)
			}
		}
	} else {
		for _, tdf := range sortedByIndex(join.Features) {
			if tdf.Label || tdf.TrainingHelper {
				continue
			}
			if !(loggingMetaData || featureVectorWithInferenceHelpers || !tdf.InferenceHelper) {
				continue
			}
			f := fgf.get(tdf.Name)
			if f == nil || !f.OfflineOnly {
				selected = append(selected, f)
			}
		}
	}
	if batch {
		for _, pk := range pks {
			if !containsFeature(selected, pk) {
				selected = append(selected, pk)
			}
		}
	}
	// join.getLeftFeatureGroup() == null holds for the root join only.
	if loggingMetaData && !join.LeftFGSet && fg.EventTime != "" {
		selected = append(selected, fgf.get(fg.EventTime))
	}
	return selected
}

func sortedByIndex(fs []spec.TDFeature) []spec.TDFeature {
	out := append([]spec.TDFeature(nil), fs...)
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j].Index < out[j-1].Index; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}

// getTrainingDatasetFeatures :1305-1323.
func getTrainingDatasetFeatures(inferenceHelperColumns, featureVectorWithInferenceHelpers bool, join spec.Join) []spec.TDFeature {
	var out []spec.TDFeature
	for _, tdf := range sortedByIndex(join.Features) {
		if inferenceHelperColumns {
			if tdf.InferenceHelper {
				out = append(out, tdf)
			}
			continue
		}
		if tdf.Label || tdf.TrainingHelper {
			continue
		}
		if !(featureVectorWithInferenceHelpers || !tdf.InferenceHelper) {
			continue
		}
		out = append(out, tdf)
	}
	return out
}

// collectSourceFeatures :361-379 + resolveCollectSources / parseStructFieldNames.
func collectSourceFeatures(join spec.Join, fg spec.FeatureGroup, fgf *fgFeatures, pks []*feature) []*feature {
	sources := append([]*feature(nil), pks...)
	for _, tdf := range join.Features {
		names := resolveCollectSources(join, fg, tdf)
		if names == nil {
			continue
		}
		for _, name := range names {
			if src := fgf.get(name); src != nil && !containsFeature(sources, src) {
				sources = append(sources, src)
			}
		}
	}
	return sources
}

// resolveCollectSources: the field names of the persisted
// array<struct<...>> type of the join's synthesized collect feature.
func resolveCollectSources(join spec.Join, fg spec.FeatureGroup, tdf spec.TDFeature) []string {
	if join.CollectN == nil || tdf.Type == nil || tdf.Name != CollectFeatureName(fg) {
		return nil
	}
	return ParseStructFieldNames(*tdf.Type)
}

// CollectFeatureName is ConstructorController.collectFeatureName.
func CollectFeatureName(fg spec.FeatureGroup) string { return fg.Name + "_collect" }

// ParseStructFieldNames parses the field names of array<struct<a:int,b:decimal(10,2)>>.
func ParseStructFieldNames(t string) []string {
	names := []string{}
	if !strings.HasPrefix(t, "array<struct<") || !strings.HasSuffix(t, ">>") {
		return names
	}
	body := t[len("array<struct<") : len(t)-2]
	depth := 0
	var field strings.Builder
	for _, c := range body {
		if c == '<' || c == '(' {
			depth++
		} else if c == '>' || c == ')' {
			depth--
		}
		if c == ',' && depth == 0 {
			names = append(names, structFieldName(field.String()))
			field.Reset()
		} else {
			field.WriteRune(c)
		}
	}
	if field.Len() > 0 {
		names = append(names, structFieldName(field.String()))
	}
	return names
}

func structFieldName(field string) string {
	if i := strings.IndexByte(field, ':'); i >= 0 {
		field = field[:i]
	}
	return strings.TrimSpace(field)
}

// aggregateSourceFeatures :384-402.
func aggregateSourceFeatures(aggSpec spec.AggSpec, fgf *fgFeatures, pks []*feature) []*feature {
	var sources []*feature
	for _, e := range aggSpec {
		if e.Key == "*" {
			if len(pks) > 0 && !containsFeature(sources, pks[0]) {
				sources = append(sources, pks[0])
			}
			continue
		}
		for _, name := range strings.Split(e.Key, ",") {
			if src := fgf.get(name); src != nil && !containsFeature(sources, src) {
				sources = append(sources, src)
			}
		}
	}
	return sources
}

// aggregateOutputs :442-472.
func aggregateOutputs(aggSpec spec.AggSpec, aliasPrefix string) string {
	var out strings.Builder
	for _, e := range aggSpec {
		for _, fn := range e.Fns {
			if out.Len() > 0 {
				out.WriteString(", ")
			}
			switch {
			case e.Key == "*":
				out.WriteString("COUNT(*) AS `" + aliasPrefix + "count`")
			case strings.Contains(e.Key, ","):
				var args strings.Builder
				for _, name := range strings.Split(e.Key, ",") {
					if args.Len() > 0 {
						args.WriteString(", ")
					}
					args.WriteString("`" + name + "`")
				}
				out.WriteString("MAX(" + strings.ToUpper(fn) + "(" + args.String() + ")) AS `" + aliasPrefix +
					strings.ReplaceAll(e.Key, ",", "_") + "_" + strings.ToLower(fn) + "`")
			default:
				out.WriteString(strings.ToUpper(fn) + "(`" + e.Key + "`) AS `" + aliasPrefix + e.Key + "_" + strings.ToLower(fn) + "`")
			}
		}
	}
	return out.String()
}

// aggregateOutputFeatureNames :610-627.
func aggregateOutputFeatureNames(aggSpec spec.AggSpec, aliasPrefix string) []string {
	var names []string
	for _, e := range aggSpec {
		for _, fn := range e.Fns {
			switch {
			case e.Key == "*":
				names = append(names, aliasPrefix+"count")
			case strings.Contains(e.Key, ","):
				names = append(names, aliasPrefix+strings.ReplaceAll(e.Key, ",", "_")+"_"+strings.ToLower(fn))
			default:
				names = append(names, aliasPrefix+e.Key+"_"+strings.ToLower(fn))
			}
		}
	}
	return names
}

// applyRonsqlAggregate :484-520.
func applyRonsqlAggregate(dto *Statement, join spec.Join, fg spec.FeatureGroup, q *query, entityKeys []*feature, batch bool, extraWhere string) error {
	if join.Aggregate == nil {
		return nil
	}
	if batch && len(entityKeys) != 1 {
		return nil
	}
	if len(entityKeys) == 0 {
		return fmt.Errorf("INTERNAL: aggregate statement without an entity key (Java throws IndexOutOfBoundsException)")
	}
	outputs := aggregateOutputs(join.Aggregate, "")
	var where strings.Builder
	if batch {
		where.WriteString("`" + entityKeys[0].Name + "` IN (?)")
	} else {
		for _, k := range entityKeys {
			if where.Len() > 0 {
				where.WriteString(" AND ")
			}
			where.WriteString("`" + k.Name + "` = ?")
		}
	}
	where.WriteString(extraWhere)
	if join.Window != nil && fg.EventTime != "" {
		where.WriteString(" AND `" + fg.EventTime + "` >= ?")
	}
	keyCol := entityKeys[0].Name
	sel := outputs
	groupBy := ""
	if batch {
		sel = "`" + keyCol + "`, " + outputs
		groupBy = " GROUP BY `" + keyCol + "`"
	}
	dto.QueryRonsql = strp("SELECT " + sel + " FROM `" + q.table() + "` WHERE " + where.String() + groupBy + ";")
	dto.RonsqlDatabase = strp(q.project)
	dto.AggregateWindow = join.Window
	return nil
}

// applyMysqlAggregate :531-580.
func applyMysqlAggregate(dto *Statement, join spec.Join, fg spec.FeatureGroup, q *query, entityKeys []*feature, batch bool, extraWhere string) {
	if join.Aggregate == nil {
		return
	}
	aliasPrefix := ""
	if dto.Prefix != nil {
		aliasPrefix = *dto.Prefix
	}
	outputs := aggregateOutputs(join.Aggregate, aliasPrefix)
	var keySelect, keySelectAliased strings.Builder
	for _, k := range entityKeys {
		if keySelect.Len() > 0 {
			keySelect.WriteString(", ")
			keySelectAliased.WriteString(", ")
		}
		keySelect.WriteString("`" + k.Name + "`")
		keySelectAliased.WriteString("`" + k.Name + "`")
		if aliasPrefix != "" {
			keySelectAliased.WriteString(" AS `" + aliasPrefix + k.Name + "`")
		}
	}
	var where strings.Builder
	if batch {
		if len(entityKeys) == 1 {
			where.WriteString(keySelect.String())
		} else {
			where.WriteString("(" + keySelect.String() + ")")
		}
		where.WriteString(" IN (?)")
	} else {
		for _, k := range entityKeys {
			if where.Len() > 0 {
				where.WriteString(" AND ")
			}
			where.WriteString("`" + k.Name + "` = ?")
		}
	}
	where.WriteString(extraWhere)
	if join.Window != nil && fg.EventTime != "" {
		where.WriteString(" AND `" + fg.EventTime + "` >= ?")
		dto.AggregateWindow = join.Window
	}
	sel := outputs
	groupBy := ""
	if batch {
		sel = keySelectAliased.String() + ", " + outputs
		groupBy = " GROUP BY " + keySelect.String()
	}
	dto.QueryOnline = strp("SELECT " + sel + " FROM `" + q.project + "`.`" + q.table() + "` WHERE " + where.String() + groupBy)
	dto.AggregateFeatureNames = aggregateOutputFeatureNames(join.Aggregate, aliasPrefix)
}

// buildDTO :629-701 (the Calcite rendering goes through mysqltwin).
func (b *builder) buildDTO(q *query, bindKeys []*feature, fgID, statementIndex int, batch bool, prefix *string,
	collectN *int, collectOrderBy *feature, collectAscending bool, extraFilters []filterLeaf, ronsqlExtraWhere string) (Statement, error) {
	if len(bindKeys) == 0 {
		return Statement{}, fmt.Errorf("INTERNAL: statement without bind keys (Java throws IndexOutOfBoundsException)")
	}
	params := make([]Param, 0, len(bindKeys))
	for i, k := range bindKeys {
		params = append(params, Param{Name: k.Name, Index: i + 1})
	}
	var cs []mysqltwin.Col
	for _, f := range q.features {
		if f == nil {
			return Statement{}, fmt.Errorf("INTERNAL: selected feature is not a column of %s (Java: NullPointerException in Calcite)", q.table())
		}
		a := f.Alias
		if a == "" {
			a = alias
		}
		out := f.Name
		if f.Prefix != nil {
			out = *f.Prefix + f.Name
		}
		cs = append(cs, mysqltwin.Col{Alias: a, Name: f.Name, Out: out})
	}
	keyNames := make([]string, len(bindKeys))
	for i, k := range bindKeys {
		keyNames[i] = k.Name
	}
	rootAlias := alias
	if q.nested != nil {
		rootAlias = q.nested.root.Alias
	}
	where := mysqltwin.KeyWhere(rootAlias, keyNames, batch)
	for _, lf := range extraFilters {
		where += " AND `" + rootAlias + "`.`" + lf.feature.Name + "` " + mysqltwin.Operator(lf.condition) + " " +
			mysqltwin.Literal(lf.value, lf.feature.Type)
	}
	t := mysqltwin.Table{DB: q.project, Name: q.table(), Alias: alias}
	var sql string
	var scan *string
	if q.nested != nil {
		sql = mysqltwin.Nested(cs, q.nested.root, q.nested.joins, where)
	} else if collectN != nil && collectOrderBy != nil {
		order := mysqltwin.Col{Alias: alias, Name: collectOrderBy.Name}
		if !batch {
			scan = strp(mysqltwin.CollectScan(cs, t, where, order))
		}
		sql = mysqltwin.CollectWindow(cs, t, where, keyNames, order, collectAscending)
	} else {
		sql = mysqltwin.PointRead(cs, t, where)
	}
	dto := Statement{
		FeatureGroupID: fgID, PreparedStatementIndex: statementIndex, PreparedStatementParameters: params,
		QueryOnline: strp(sql), Prefix: prefix,
	}
	if collectOrderBy != nil {
		dto.CollectN = collectN
	}
	if collectN != nil && collectOrderBy != nil {
		dto.CollectFeatureName = strp(CollectFeatureName(q.fg))
		dto.CollectOrderBy = strp(collectOrderBy.Name)
		dto.CollectAscending = boolp(collectAscending)
		dto.CollectFilterApplied = boolp(len(extraFilters) > 0)
		names := make([]string, 0, len(q.features))
		for _, f := range q.features {
			names = append(names, f.Name)
		}
		dto.CollectSourceFeatures = names
		dto.QueryOnlineScan = scan
	}
	if collectN != nil && collectOrderBy != nil && !batch {
		dto.QueryRonsql = strp(buildRonsqlCollectTemplate(q, bindKeys, collectOrderBy, *collectN, ronsqlExtraWhere))
		dto.RonsqlDatabase = strp(q.project)
	}
	return dto, nil
}

// conjunctiveFilterConditions :703-718.  Returns isNil when the tree
// contains an OR (Java returns null).
func conjunctiveFilterConditions(filters []spec.Filter) ([]spec.Filter, bool) {
	if len(filters) == 0 {
		return []spec.Filter{}, false
	}
	var out []spec.Filter
	for _, f := range filters {
		if f.Logic == spec.LogicOr {
			return nil, true
		}
		if f.Feature != "" || f.Condition != nil || f.Value != nil {
			out = append(out, f)
		}
	}
	if out == nil {
		out = []spec.Filter{}
	}
	return out, false
}

// renderRonsqlCondition :723-751.
func renderRonsqlCondition(cond spec.Filter, fgf *fgFeatures) (string, bool) {
	if cond.ValueFeatureGroupID != nil || cond.Value == nil || cond.Condition == nil || !renderableConditions[*cond.Condition] {
		return "", false
	}
	f := fgf.get(cond.Feature)
	if f == nil {
		return "", false
	}
	literal, ok := renderRonsqlLiteral(*cond.Value, f.Type)
	if !ok {
		return "", false
	}
	var op string
	switch *cond.Condition {
	case spec.CondEquals:
		op = "="
	case spec.CondNotEquals:
		op = "<>"
	case spec.CondGreaterThan:
		op = ">"
	case spec.CondGreaterThanOrEqual:
		op = ">="
	case spec.CondLessThan:
		op = "<"
	case spec.CondLessThanOrEqual:
		op = "<="
	case spec.CondLike:
		op = "LIKE"
	default:
		return "", false
	}
	return "`" + cond.Feature + "` " + op + " " + literal, true
}

// renderRonsqlLiteral :754-770.
func renderRonsqlLiteral(value, featureType string) (string, bool) {
	t := strings.ToLower(featureType)
	for _, p := range numericTypePrefixes {
		if strings.HasPrefix(t, p) {
			if numericLiteral.MatchString(value) {
				return value, true
			}
			return "", false
		}
	}
	if strings.HasPrefix(t, "boolean") {
		return "", false
	}
	for i := 0; i < len(value); i++ {
		if value[i] < 0x20 || value[i] == '\\' {
			return "", false
		}
	}
	return "'" + strings.ReplaceAll(value, "'", "''") + "'", true
}

// buildRonsqlCollectTemplate :780-800.
func buildRonsqlCollectTemplate(q *query, entityKeys []*feature, orderBy *feature, n int, extraWhere string) string {
	var cols strings.Builder
	for _, f := range q.features {
		if cols.Len() > 0 {
			cols.WriteString(", ")
		}
		cols.WriteString("`" + f.Name + "`")
	}
	var where strings.Builder
	for _, k := range entityKeys {
		if where.Len() > 0 {
			where.WriteString(" AND ")
		}
		where.WriteString("`" + k.Name + "` = ?")
	}
	return "WITH t AS (SELECT " + cols.String() + " FROM `" + q.table() + "` WHERE " + where.String() + extraWhere +
		" ORDER BY `" + orderBy.Name + "` DESC" + " LIMIT " + fmt.Sprintf("%d", n) + ") SELECT " + cols.String() + " FROM t;"
}

// ---- snowflake schema (:805-1180) -----------------------------------------

// retrieveRightJoinsLists (NestedTrainingDatasetJoinTree): STAR joins and
// the roots of nested subtrees.
func retrieveRightJoinsLists(joins []spec.Join) (star, nested []spec.Join) {
	parentIndexes := map[int]bool{}
	for _, j := range joins {
		parentIndexes[j.Parent] = true
	}
	for _, j := range joins {
		if j.Index == 0 || (j.Parent == 0 && !parentIndexes[j.Index]) {
			star = append(star, j)
		} else if j.Parent == 0 {
			nested = append(nested, j)
		}
	}
	return star, nested
}

// constructTree (NestedTrainingDatasetJoinTree.constructTreeRecursive): the
// subtree rooted at root in depth-first, list order, recursion limit 20.
func constructTree(root spec.Join, joins []spec.Join) ([]spec.Join, error) {
	var tree []spec.Join
	var rec func(cur spec.Join, limit int) error
	rec = func(cur spec.Join, limit int) error {
		if limit <= 0 {
			return spec.Gate(spec.CodeNestedJoinsRecursionExceeded,
				"current recursion limit exceeded, limit: %d, root training dataset join id: %d", limit, root.Index+1)
		}
		tree = append(tree, cur)
		for _, j := range joins {
			if j.Parent == cur.Index {
				if err := rec(j, limit-1); err != nil {
					return err
				}
			}
		}
		return nil
	}
	if err := rec(root, 20); err != nil {
		return nil, err
	}
	return tree, nil
}

func (b *builder) createSnowflakePreparedStatementDTOS(joins []spec.Join, hasFilters bool) ([]Statement, error) {
	if hasFilters {
		for _, j := range joins {
			if j.CollectN != nil || j.Aggregate != nil {
				return nil, spec.Gate(spec.CodeCollectUnsupportedOnlineFilt,
					"snowflake-schema feature views cannot apply their filters to online collect/aggregation statements")
			}
		}
	}
	star, nested := retrieveRightJoinsLists(joins)
	var out []Statement
	if len(star) > 0 {
		dtos, err := b.createServingPreparedStatementDTOS(star, []spec.Filter{}, false)
		if err != nil {
			return nil, err
		}
		out = dtos
	}
	return b.constructSnowflakeJoinsDTO(joins, nested, out)
}

// validateExtractPrimaryFeatures :1191-1222.
func (b *builder) validateExtractPrimaryFeatures(join spec.Join) ([]*feature, error) {
	fg := b.fgs[join.FG]
	if !fg.OnlineEnabled() {
		return nil, notOnlineEnabled(fg)
	}
	fgf := b.featuresOf(fg, join.Prefix)
	pks := primaryKeys(fgf)
	if len(pks) == 0 {
		return nil, primaryKeyRequired()
	}
	return pks, nil
}

func (b *builder) constructSnowflakeJoinsDTO(joins []spec.Join, roots []spec.Join, out []Statement) ([]Statement, error) {
	for _, root := range roots {
		childJoins, err := constructTree(root, joins)
		if err != nil {
			return nil, err
		}
		for _, cj := range childJoins {
			if cj.Index == root.Index {
				continue
			}
			if _, err := b.validateExtractPrimaryFeatures(cj); err != nil {
				return nil, err
			}
		}
		rootPKs, err := b.validateExtractPrimaryFeatures(root)
		if err != nil {
			return nil, err
		}
		// nestedLeftQuery = trainingDatasetController.getQuery(childJoins, nestedFeatures, ...)
		q, err := b.nestedQueryOf(root, childJoins, rootPKs)
		if err != nil {
			return nil, err
		}
		fgFeaturesByID := map[int][]spec.Feature{}
		for _, cj := range childJoins {
			if _, ok := fgFeaturesByID[cj.FG]; !ok {
				fgFeaturesByID[cj.FG] = b.fgs[cj.FG].Features
			}
		}
		templates := b.buildRonsqlSnowflakeTemplates(root, childJoins, rootPKs, fgFeaturesByID)
		dto, err := b.buildDTO(q, rootPKs, b.fgs[root.FG].ID, root.Index, b.opt.Batch, root.Prefix, nil, nil, false, nil, "")
		if err != nil {
			return nil, err
		}
		dto.SnowflakeTemplate = boolp(true)
		if templates != nil {
			dto.SnowflakeTemplates = templates
			dto.RonsqlDatabase = strp(q.project)
		}
		out = append(out, dto)
	}
	return out, nil
}

// nestedQueryOf mirrors what TrainingDatasetController.getQuery produces for
// a snowflake subtree and the join validation it performs on the way
// (QueryController.checkFeatureExistsAndSetAttributes / checkJoinOnIsPrimaryKey).
func (b *builder) nestedQueryOf(root spec.Join, childJoins []spec.Join, rootPKs []*feature) (*query, error) {
	rootFG := b.fgs[root.FG]
	aliasOf := map[int]string{}
	for i, cj := range childJoins {
		aliasOf[cj.Index] = fmt.Sprintf("fg%d", i)
	}
	var features []*feature
	addFeatures := func(cj spec.Join) {
		fg := b.fgs[cj.FG]
		fgf := b.featuresOf(fg, cj.Prefix)
		for _, tdf := range getTrainingDatasetFeatures(b.opt.InferenceHelpers, b.opt.Logging || b.opt.VectorWithHelpers, cj) {
			f := fgf.get(tdf.Name)
			if f != nil {
				cp := *f
				cp.Alias = aliasOf[cj.Index]
				features = append(features, &cp)
			} else {
				features = append(features, nil)
			}
		}
	}
	for _, cj := range childJoins {
		if cj.Index == root.Index {
			continue
		}
		addFeatures(cj)
	}
	addFeatures(root)
	if b.opt.Batch {
		for _, pk := range rootPKs {
			cp := *pk
			cp.Alias = aliasOf[root.Index]
			features = append(features, &cp)
		}
	}
	nq := &nestedQuery{root: mysqltwin.Table{DB: rootFG.OnlineDatabase(), Name: rootFG.TableName(), Alias: aliasOf[root.Index]}}
	for _, cj := range childJoins {
		if cj.Index == root.Index {
			continue
		}
		parent := childJoinByIndex(childJoins, cj.Parent)
		parentFG := b.fgs[parent.FG]
		childFG := b.fgs[cj.FG]
		var on [][2]string
		for _, c := range cj.On {
			if _, ok := parentFG.Feature(c[0]); !ok {
				return nil, spec.Gate(spec.CodeFeatureDoesNotExist, "Could not find Join feature %s in feature group: %s", c[0], parentFG.Name)
			}
			if _, ok := childFG.Feature(c[1]); !ok {
				return nil, spec.Gate(spec.CodeFeatureDoesNotExist, "Could not find Join feature %s in feature group: %s", c[1], childFG.Name)
			}
			on = append(on, [2]string{c[0], c[1]})
		}
		if err := checkJoinOnIsPrimaryKey(childFG, cj.On); err != nil {
			return nil, err
		}
		nq.joins = append(nq.joins, mysqltwin.JoinClause{Type: cj.Type,
			Table:  mysqltwin.Table{DB: childFG.OnlineDatabase(), Name: childFG.TableName(), Alias: aliasOf[cj.Index]},
			Parent: aliasOf[parent.Index], On: on})
	}
	return &query{project: rootFG.OnlineDatabase(), fg: rootFG, features: features, nested: nq}, nil
}

func childJoinByIndex(joins []spec.Join, index int) spec.Join {
	for _, j := range joins {
		if j.Index == index {
			return j
		}
	}
	return spec.Join{}
}

// checkJoinOnIsPrimaryKey (QueryController): the right-hand join columns
// must be exactly the child's primary key.
func checkJoinOnIsPrimaryKey(child spec.FeatureGroup, on [][2]string) error {
	joinOn := map[string]bool{}
	for _, c := range on {
		joinOn[c[1]] = true
	}
	pk := map[string]bool{}
	for _, f := range child.Features {
		if f.Primary {
			pk[f.Name] = true
		}
	}
	for _, c := range on {
		if !pk[c[1]] {
			return spec.Gate(spec.CodeForeignKeyNotPrimaryKey, "%s is not primary key in feature group: %s", c[1], child.Name)
		}
	}
	for _, f := range child.Features {
		if f.Primary && !joinOn[f.Name] {
			return spec.Gate(spec.CodeJoinOnPartialPrimaryKey,
				"%s is not included in the list of keys to make the join on, but is a part of primary key of feature group: %s", f.Name, child.Name)
		}
	}
	return nil
}

// buildRonsqlSnowflakeTemplates :966-1062.
func (b *builder) buildRonsqlSnowflakeTemplates(root spec.Join, childJoins []spec.Join, rootPKs []*feature, fgFeaturesByID map[int][]spec.Feature) []string {
	if b.opt.Batch && len(rootPKs) != 1 {
		return nil
	}
	var nested []spec.Join
	for _, cj := range childJoins {
		if cj.Index != root.Index {
			nested = append(nested, cj)
		}
	}
	if len(nested) == 0 {
		return nil
	}
	allInner, allLeft := true, true
	rootFS := b.fgs[root.FG].FeaturestoreID
	for _, cj := range nested {
		if cj.Type != spec.JoinInner && cj.Type != spec.JoinLeft {
			return nil
		}
		if cj.Type != spec.JoinInner {
			allInner = false
		}
		if cj.Type != spec.JoinLeft {
			allLeft = false
		}
		if b.fgs[cj.FG].FeaturestoreID != rootFS {
			return nil
		}
		if len(cj.On) == 0 {
			return nil
		}
		childPKs := map[string]bool{}
		for _, f := range fgFeaturesByID[cj.FG] {
			if f.Primary {
				childPKs[f.Name] = true
			}
		}
		right := map[string]bool{}
		for _, c := range cj.On {
			right[c[1]] = true
		}
		if len(right) != len(childPKs) {
			return nil
		}
		for k := range right {
			if !childPKs[k] {
				return nil
			}
		}
	}
	byIndex := map[int]spec.Join{}
	for _, cj := range nested {
		byIndex[cj.Index] = cj
	}
	if allInner {
		t := b.buildSnowflakeStatement(root, nested, nested, rootPKs, fgFeaturesByID)
		if t == nil {
			return nil
		}
		return []string{*t}
	}
	if !allLeft {
		return nil
	}
	var templates []string
	for _, target := range nested {
		var chain []spec.Join
		cursor, ok := target, true
		for ok && cursor.Parent != root.Index {
			chain = append([]spec.Join{cursor}, chain...)
			cursor, ok = byIndex[cursor.Parent]
		}
		if !ok {
			return nil
		}
		chain = append([]spec.Join{cursor}, chain...)
		t := b.buildSnowflakeStatement(root, chain, []spec.Join{target}, rootPKs, fgFeaturesByID)
		if t == nil {
			continue
		}
		templates = append(templates, *t)
	}
	if len(templates) == 0 {
		return nil
	}
	return templates
}

// buildSnowflakeStatement :1067-1180.
func (b *builder) buildSnowflakeStatement(root spec.Join, traversed, projection []spec.Join, rootPKs []*feature, fgFeaturesByID map[int][]spec.Feature) *string {
	var cteColumns []string
	seen := map[string]bool{}
	addCol := func(c string) {
		if !seen[c] {
			seen[c] = true
			cteColumns = append(cteColumns, c)
		}
	}
	if b.opt.Batch {
		for _, pk := range rootPKs {
			addCol(pk.Name)
		}
	}
	var joinClauses strings.Builder
	for _, cj := range traversed {
		parentIsRoot := cj.Parent == root.Index
		parentAlias := "b"
		if !parentIsRoot {
			parentAlias = fmt.Sprintf("j%d", cj.Parent)
		}
		childAlias := fmt.Sprintf("j%d", cj.Index)
		var on strings.Builder
		for _, c := range cj.On {
			if parentIsRoot {
				addCol(c[0])
			}
			if on.Len() > 0 {
				on.WriteString(" AND ")
			}
			on.WriteString("`" + childAlias + "`.`" + c[1] + "` = `" + parentAlias + "`.`" + c[0] + "`")
		}
		joinClauses.WriteString(" JOIN `" + b.fgs[cj.FG].TableName() + "` AS `" + childAlias + "` ON " + on.String())
	}
	var projections strings.Builder
	for _, cj := range projection {
		childAlias := fmt.Sprintf("j%d", cj.Index)
		prefix := cj.PrefixOrEmpty()
		for _, tdf := range getTrainingDatasetFeatures(b.opt.InferenceHelpers, b.opt.Logging || b.opt.VectorWithHelpers, cj) {
			if projections.Len() > 0 {
				projections.WriteString(", ")
			}
			projections.WriteString("`" + childAlias + "`.`" + tdf.Name + "` AS `" + prefix + tdf.Name + "`")
		}
	}
	if projections.Len() == 0 {
		return nil
	}
	rootColumns := map[string]bool{}
	for _, f := range fgFeaturesByID[root.FG] {
		rootColumns[f.Name] = true
	}
	for _, c := range cteColumns {
		if !rootColumns[c] {
			return nil
		}
	}
	var cteSelect strings.Builder
	for _, c := range cteColumns {
		cteSelect.WriteString("`" + c + "`, ")
	}
	var where strings.Builder
	if b.opt.Batch {
		where.WriteString("`" + rootPKs[0].Name + "` IN (?)")
	} else {
		for _, pk := range rootPKs {
			if where.Len() > 0 {
				where.WriteString(" AND ")
			}
			where.WriteString("`" + pk.Name + "` = ?")
		}
	}
	groupBy := ""
	for i, c := range cteColumns {
		if i > 0 {
			groupBy += ", "
		}
		groupBy += "`" + c + "`"
	}
	if b.opt.Batch {
		for _, pk := range rootPKs {
			projections.WriteString(", `b`.`" + pk.Name + "` AS `" + pk.Name + "`")
		}
	}
	s := "WITH `b` AS (SELECT " + cteSelect.String() + "COUNT(*) AS `hw_cnt` FROM `" + b.fgs[root.FG].TableName() +
		"` WHERE " + where.String() + " GROUP BY " + groupBy + ") SELECT " + projections.String() + " FROM `b`" +
		joinClauses.String() + ";"
	return &s
}
