name: build-deploy

on:
  # Launch on manual trigger
  workflow_dispatch:
  push:
    branches:
    - 22.10.[0-9]+
    - 21.04.[0-9]+
  # TODO: Remove this once done with testing
  pull_request:
    # Not running on "closed" - that is taken care of by "push" (if merged)
    types: [opened, synchronize, reopened]

jobs:
  build-deploy:
    # if: github.repository == 'logicalclocks/rondb'
    runs-on: macos-13-xlarge

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Build with Docker
        run: |  
          export DOCKER_CLI_EXPERIMENTAL=enabled
          export BUILDKIT_PROGRESS=plain

          docker buildx build . \
            -f Dockerfile.ubuntu22 \
            --tag rondb-build-all:22.10.1 \
            --target build-all \
            --no-cache \
            --build-arg BUILD_THREADS=$BUILD_CORES \
            --build-arg RELEASE_TARBALL=1 # \
            # --build-arg RELEASE_FINAL_CLUSTERJ=1 \
            # --build-arg DEPLOY_TO_REPO=1 \
